import os
import json

PRODUCTS = [
    # 1. Men's Biker Jackets (Black, Brown, Red)
    {
        "id": "prod_mj_biker_black",
        "slug": "mens-full-grain-leather-biker-jacket-black",
        "title": "Obsidian Full-Grain Leather Asymmetric Biker Jacket",
        "subtitle": "1.1mm Drum-Dyed Indian Lambskin • Heavy YKK Zippers & Quilted Shoulders",
        "shortDescription": "Iconic asymmetric motorcycle jacket tailored from supple 1.1mm full-grain lambskin with diamond-quilted shoulders and waist belt.",
        "description": "Crafted for decades of wear. Our signature obsidian biker jacket features hand-selected 1.1mm drum-dyed full-grain lambskin that breaks in to mould to your body. Equipped with heavy-duty silver YKK zippers, snap-down lapels, diamond-stitched impact shoulders, and an adjustable waist belt.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers", "col_bestsellers"],
        "tags": ["leather", "biker", "jacket", "men", "black", "moto", "bestseller"],
        "price": 18999,
        "mrp": 24999,
        "costPrice": 7800,
        "badge": "Bestseller",
        "image": "/images/mens_biker_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Vegetable-Tanned Indian Lambskin (1.1mm), 100% Viscose Satin Lining",
        "fit": "Tailored European Rider Fit (True to size). Size up for layering over thick knitwear."
    },
    {
        "id": "prod_mj_biker_brown",
        "slug": "mens-vintage-distressed-leather-moto-jacket-brown",
        "title": "Vintage Distressed Tobacco Leather Moto Jacket",
        "subtitle": "1.2mm Buffed Cowhide with Natural Pull-Up Patina • Antique Brass Hardware",
        "shortDescription": "Rugged motorcycle jacket cut from distressed tobacco cowhide leather that develops a unique natural patina with age.",
        "description": "Inspired by vintage cafe culture. Tailored from 1.2mm buffed cowhide with natural pull-up oils that highlight character lines over time. Features antique brass zip closures, quilted arm gussets, buckle collar tab, and two zippered chest utility pockets.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers"],
        "tags": ["leather", "moto", "jacket", "men", "brown", "tobacco", "vintage"],
        "price": 19499,
        "mrp": 25999,
        "costPrice": 8200,
        "badge": "Heritage",
        "image": "/images/mens_jacket_brown.jpg",
        "color": "Tobacco Brown",
        "colorHex": "#6E4120",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Buffed Oil-Tanned Indian Cowhide (1.2mm), Quilted Bemberg Lining",
        "fit": "Classic Regular Fit with gusseted action-back shoulders for riding comfort."
    },
    {
        "id": "prod_mj_biker_red",
        "slug": "mens-oxblood-crimson-leather-biker-jacket-red",
        "title": "Oxblood Crimson Leather Asymmetric Biker Jacket",
        "subtitle": "Drum-Dyed Wine Red Lambskin • Gunmetal Hardware & Symmetrical Contours",
        "shortDescription": "Striking deep oxblood red leather biker jacket with gunmetal zippers, snap lapels, and tailored waist tabs.",
        "description": "A sophisticated statement piece. Handcrafted from drum-dyed oxblood lambskin with deep wine undertones. Finished with gunmetal hardware, diagonal zip front, snap-fastened lapels, zippered sleeve cuffs, and twin interior welt pockets.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers"],
        "tags": ["leather", "biker", "jacket", "men", "red", "oxblood", "statement"],
        "price": 19999,
        "mrp": 26999,
        "costPrice": 8400,
        "badge": "Limited Edition",
        "image": "/images/mens_jacket_red.jpg",
        "color": "Oxblood Red",
        "colorHex": "#641920",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Full-Grain Lambskin (1.0mm), Silk-Blend Cupro Lining",
        "fit": "Slim Rider Fit with tapered waist."
    },

    # 2. Women's Biker Jackets (Black, Brown, Red)
    {
        "id": "prod_wj_biker_black",
        "slug": "womens-cropped-nappa-leather-biker-jacket-black",
        "title": "Cropped Obsidian Nappa Leather Biker Jacket",
        "subtitle": "0.9mm Glove-Soft Italian Nappa • Polished Silver Hardware & Belted Hem",
        "shortDescription": "Feminine cropped moto silhouette crafted from butter-soft black nappa leather with polished silver zippers.",
        "description": "The quintessential leather jacket. Tailored with a cropped waistline and contoured back seams to flatter every silhouette. Cut from glove-soft 0.9mm black nappa leather with polished chrome hardware, zip sleeve cuffs, and snap collar.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers", "col_bestsellers"],
        "tags": ["leather", "biker", "jacket", "women", "black", "cropped", "bestseller"],
        "price": 17999,
        "mrp": 23499,
        "costPrice": 7200,
        "badge": "Bestseller",
        "image": "/images/womens_biker_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Italian-Grade Lambskin Nappa (0.9mm), Stretch Satin Lining",
        "fit": "Tailored Cropped Slim Fit. Hits right at natural waistline."
    },
    {
        "id": "prod_wj_biker_brown",
        "slug": "womens-cognac-tan-butter-soft-leather-moto-jacket",
        "title": "Cognac Tan Butter-Soft Leather Moto Jacket",
        "subtitle": "Vegetable-Tanned Caramel Goat Nappa • Brushed Gold Hardware",
        "shortDescription": "Luxurious caramel cognac leather jacket with brushed gold zippers, princess seams, and point lapels.",
        "description": "Warm, elegant, and versatile. Crafted from vegetable-tanned goat nappa leather in rich golden cognac. Features brushed gold zip accents, diagonal chest pockets, and refined seam detailing.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers"],
        "tags": ["leather", "moto", "jacket", "women", "brown", "cognac", "tan"],
        "price": 18499,
        "mrp": 24299,
        "costPrice": 7400,
        "badge": "New Season",
        "image": "/images/womens_jacket_brown.jpg",
        "color": "Cognac Tan",
        "colorHex": "#A86632",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Vegetable-Tanned Goat Nappa (0.9mm), Warm Ivory Viscose Lining",
        "fit": "Tailored Feminine Fit with shaped side panels."
    },
    {
        "id": "prod_wj_biker_red",
        "slug": "womens-deep-burgundy-red-belted-leather-biker",
        "title": "Deep Burgundy Red Belted Leather Biker Jacket",
        "subtitle": "Dark Wine Lambskin • Brushed Silver Buckle & Asymmetric Zip",
        "shortDescription": "Deep wine red lambskin leather biker jacket featuring an integrated waist belt and asymmetric zip front.",
        "description": "Richly saturated in dark cherry wine tones. Built from full-grain lambskin with natural suppleness. Features an asymmetric front zipper, snap collar, zippered hand pockets, and a classic buckled hem belt.",
        "productType": "jacket",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers"],
        "tags": ["leather", "biker", "jacket", "women", "red", "burgundy", "belted"],
        "price": 18999,
        "mrp": 24999,
        "costPrice": 7600,
        "badge": "Trending",
        "image": "/images/womens_jacket_red.jpg",
        "color": "Burgundy Red",
        "colorHex": "#6E1C26",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Lambskin Leather (1.0mm), Silk Cupro Lining",
        "fit": "Contoured Hourglass Cut with adjustable buckled waist."
    },

    # 3. Women's Leather Skirts (Black, Brown, Red)
    {
        "id": "prod_wsk_aline_black",
        "slug": "womens-high-waisted-black-leather-aline-midi-skirt",
        "title": "High-Waisted Black Leather A-Line Midi Skirt",
        "subtitle": "Full-Grain Lambskin Nappa • Front Walking Slit & Panel Stitching",
        "shortDescription": "Flattering high-waisted A-line midi skirt cut from supple black lambskin nappa with clean vertical panel seams and a front slit.",
        "description": "An architectural staple for the modern wardrobe. Features a high-waisted tailored waistband that flares gently into an A-line midi drape. Cut with vertical seam panels and a subtle front-left walking slit. Fully lined in breathable silk-blend cupro with an invisible side zip.",
        "productType": "skirt",
        "categoryId": "cat_skirts",
        "categoryAncestry": ["cat_women_leather", "cat_skirts"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_bestsellers"],
        "tags": ["leather", "skirt", "midi", "aline", "women", "black", "bestseller"],
        "price": 11999,
        "mrp": 15499,
        "costPrice": 4800,
        "badge": "Bestseller",
        "image": "/images/womens_skirt_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Black Lambskin Nappa (0.8mm), Breathable Silk-Blend Cupro Lining",
        "fit": "High-Rise A-Line Midi (Length: 76cm). Sits at natural high waist."
    },
    {
        "id": "prod_wsk_pencil_brown",
        "slug": "womens-chestnut-brown-paneled-leather-pencil-skirt",
        "title": "Chestnut Brown Paneled Leather Pencil Skirt",
        "subtitle": "Vegetable-Tanned Saddle Leather • Exposed Rear Zip & Walking Vent",
        "shortDescription": "Knee-length tailored pencil skirt in rich chestnut brown leather with refined topstitched panels.",
        "description": "Structured elegance for business and evenings. Cut from vegetable-tanned chestnut leather that retains its sleek form. Features vertical contour panels, an exposed antique brass back zipper, and a rear walking vent for effortless movement.",
        "productType": "skirt",
        "categoryId": "cat_skirts",
        "categoryAncestry": ["cat_women_leather", "cat_skirts"],
        "collectionIds": ["col_all_leather", "col_womens_collection"],
        "tags": ["leather", "skirt", "pencil", "women", "brown", "chestnut", "workwear"],
        "price": 12499,
        "mrp": 16299,
        "costPrice": 5100,
        "badge": "Artisan Edit",
        "image": "/images/womens_skirt_brown.jpg",
        "color": "Chestnut Brown",
        "colorHex": "#8C461E",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Vegetable-Tanned Goat Leather (0.9mm), Stretch Satin Lining",
        "fit": "Tailored High-Waist Pencil Cut (Length: 62cm)."
    },
    {
        "id": "prod_wsk_wrap_red",
        "slug": "womens-burgundy-red-leather-buckle-wrap-mini-skirt",
        "title": "Burgundy Red Leather Buckle Wrap Mini Skirt",
        "subtitle": "Supple Deep Crimson Calfskin • Polished Oval Gold Buckle Clasp",
        "shortDescription": "High-waisted wrap mini skirt in deep oxblood red leather with an asymmetric front and gold oval buckle fastening.",
        "description": "Bold yet refined. Tailored with an overlapping wrap front secured by an adjustable gold-tone buckle belt. Crafted from supple deep burgundy calfskin leather that resists creasing and moves with you.",
        "productType": "skirt",
        "categoryId": "cat_skirts",
        "categoryAncestry": ["cat_women_leather", "cat_skirts"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_new_arrivals"],
        "tags": ["leather", "skirt", "mini", "wrap", "women", "red", "burgundy"],
        "price": 9999,
        "mrp": 13499,
        "costPrice": 4100,
        "badge": "New Season",
        "image": "/images/womens_skirt_red.jpg",
        "color": "Burgundy Red",
        "colorHex": "#6E1C26",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Crimson Calfskin (0.9mm), Soft Viscose Lining",
        "fit": "High-Waist Wrap Mini Cut (Length: 46cm)."
    },

    # 4. Men's Leather Coats (Black, Brown, Red)
    {
        "id": "prod_mc_car_black",
        "slug": "mens-single-breasted-black-leather-car-coat",
        "title": "Obsidian Tailored Single-Breasted Leather Car Coat",
        "subtitle": "Knee-Length Full-Grain Lambskin • Horn Buttons & Dual Internal Passport Pockets",
        "shortDescription": "Knee-length single-breasted leather overcoat tailored from rich full-grain black lambskin with horn buttons.",
        "description": "The peak of sartorial leather craft. Single-breasted tailored silhouette with clean notch lapels, horn button front, vertical welt pockets, center back vent, and two secure internal passport pockets. Sits comfortably over suits or heavy knitwear.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_men_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_coats_trench", "col_bestsellers"],
        "tags": ["leather", "coat", "overcoat", "men", "black", "trench", "bestseller"],
        "price": 27999,
        "mrp": 36999,
        "costPrice": 11500,
        "badge": "Atelier Masterpiece",
        "image": "/images/mens_coat_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Vegetable-Tanned Lambskin (1.1mm), Heavy Bemberg Silk Lining",
        "fit": "Tailored Overcoat Cut (Knee Length). Designed to layer over blazers."
    },
    {
        "id": "prod_mc_trench_brown",
        "slug": "mens-saddle-brown-belted-leather-trench-coat",
        "title": "Saddle Brown Double-Breasted Belted Leather Trench Coat",
        "subtitle": "1.3mm Bourbon Vegetable-Tanned Cowhide • Storm Flap & Leather Buckle Belt",
        "shortDescription": "Heritage double-breasted leather trench coat in saddle brown with storm flaps, epaulettes, and leather waist belt.",
        "description": "An imposing heritage coat built from heavyweight 1.3mm bourbon cowhide. Double-breasted ten-button front with tortoise-shell horn buttons, adjustable cuff buckles, back storm shield, and a matching leather tie belt.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_men_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_coats_trench", "col_new_arrivals"],
        "tags": ["leather", "trench", "coat", "men", "brown", "saddle", "double_breasted"],
        "price": 29999,
        "mrp": 39999,
        "costPrice": 12800,
        "badge": "Signature",
        "image": "/images/mens_coat_brown.jpg",
        "color": "Saddle Brown",
        "colorHex": "#A05F2D",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Vegetable-Tanned Bourbon Cowhide (1.3mm), Quilted Viscose Lining",
        "fit": "Generous Trench Cut with cinching waist belt (Mid-Calf Length)."
    },
    {
        "id": "prod_mc_car_red",
        "slug": "mens-burgundy-red-structured-leather-car-coat",
        "title": "Burgundy Red Structured Leather Car Coat",
        "subtitle": "Drum-Dyed Oxblood Calfskin • Point Collar & Concealed Placket",
        "shortDescription": "Modern structured car coat in rich burgundy red calfskin with a concealed button placket and slash hand pockets.",
        "description": "Clean minimalist lines meet deep wine red leather. Tailored with a sharp point collar, concealed button closure, slanted hand-warmer pockets, and structured shoulders. Lined in lightweight silk-blend twill.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_men_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_coats_trench"],
        "tags": ["leather", "coat", "car_coat", "men", "red", "oxblood", "burgundy"],
        "price": 28499,
        "mrp": 37500,
        "costPrice": 11800,
        "badge": "Exclusive",
        "image": "/images/mens_coat_red.jpg",
        "color": "Burgundy Red",
        "colorHex": "#6E1C26",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Oxblood Calfskin (1.1mm), Silk-Blend Twill Lining",
        "fit": "Tailored Mid-Thigh Car Coat Fit."
    },

    # 5. Women's Leather Coats (Black, Brown, Red)
    {
        "id": "prod_wc_trench_black",
        "slug": "womens-double-breasted-black-leather-trench-coat",
        "title": "Double-Breasted Obsidian Nappa Leather Trench Coat",
        "subtitle": "Full-Length Italian Nappa • Leather Waist Belt & Storm Shield",
        "shortDescription": "Full-length double-breasted black leather trench coat featuring a waist-cinching belt and storm flap.",
        "description": "Unrivaled luxury and presence. Crafted from feather-light yet durable Italian-grade black nappa leather that falls in graceful folds. Double-breasted button front, epaulettes, matching leather belt with covered buckle, and wrist cinch straps.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_women_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_coats_trench", "col_new_arrivals"],
        "tags": ["leather", "trench", "coat", "women", "black", "longline", "luxury"],
        "price": 26999,
        "mrp": 35999,
        "costPrice": 10900,
        "badge": "New Arrival",
        "image": "/images/womens_coat_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Glove-Soft Lambskin Nappa (0.9mm), 100% Viscose Satin Lining",
        "fit": "Longline Belted Silhouette (Length: 115cm)."
    },
    {
        "id": "prod_wc_trench_brown",
        "slug": "womens-caramel-tan-butter-soft-leather-trench-coat",
        "title": "Caramel Tan Butter-Soft Leather Trench Coat",
        "subtitle": "Glove-Soft Golden Caramel Lambskin • Wrap Belt & Relaxed Lapels",
        "shortDescription": "Warm caramel tan longline leather trench coat with a fluid drape and matching self-tie sash belt.",
        "description": "Effortless warmth and sophistication. Handcrafted from butter-soft golden caramel lambskin. Designed with fluid relaxed lapels, deep welt pockets, and a wide leather sash belt that cinches the waist.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_women_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_coats_trench"],
        "tags": ["leather", "trench", "coat", "women", "brown", "caramel", "tan"],
        "price": 27499,
        "mrp": 36499,
        "costPrice": 11200,
        "badge": "Signature",
        "image": "/images/womens_coat_brown.jpg",
        "color": "Caramel Tan",
        "colorHex": "#A86632",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Caramel Lambskin (0.9mm), Warm Ivory Silk-Blend Lining",
        "fit": "Fluid Relaxed Trench Fit with Self-Tie Belt."
    },
    {
        "id": "prod_wc_trench_red",
        "slug": "womens-deep-wine-red-tailored-leather-belted-coat",
        "title": "Deep Wine Red Tailored Leather Belted Coat",
        "subtitle": "Oxblood Calfskin • Gold Buckle Belt & Structured Shoulders",
        "shortDescription": "Tailored longline coat in deep oxblood wine red leather with structured shoulders and a gold-buckled waist belt.",
        "description": "A show-stopping coat tailored to perfection. Deep wine red calfskin with a subtle natural sheen. Features sharp tailored lapels, structured shoulder padding, gold-accented waist belt, and deep hand pockets.",
        "productType": "coat",
        "categoryId": "cat_coats",
        "categoryAncestry": ["cat_women_leather", "cat_coats"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_coats_trench"],
        "tags": ["leather", "coat", "trench", "women", "red", "wine", "oxblood"],
        "price": 27999,
        "mrp": 36999,
        "costPrice": 11400,
        "badge": "Runway Edit",
        "image": "/images/womens_coat_red.jpg",
        "color": "Wine Red",
        "colorHex": "#6E1C26",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Oxblood Calfskin (1.0mm), Rich Burgundy Cupro Lining",
        "fit": "Structured Feminine Longline Cut (Length: 110cm)."
    },

    # 6. Men's Bomber / Flight Jackets (Black, Brown, Red)
    {
        "id": "prod_mb_ma1_black",
        "slug": "mens-ma1-lambskin-flight-bomber-jacket-black",
        "title": "MA-1 Lambskin Flight Bomber Jacket in Obsidian Black",
        "subtitle": "Full-Grain Black Lambskin • Heavy Wool-Blend Ribbing & Sleeve Utility Zip",
        "shortDescription": "Classic military MA-1 flight jacket crafted from supple black lambskin with dense wool ribbing and heavy brass zippers.",
        "description": "The timeless pilot silhouette upgraded to luxury standards. Constructed from 1.1mm full-grain black lambskin with dense wool-blend ribbed collar, cuffs, and hem. Features a heavy antique brass center zipper, snap hand pockets, and the signature zippered utility arm pocket.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_men_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_bombers_flight"],
        "tags": ["leather", "bomber", "flight", "men", "black", "ma1", "aviator"],
        "price": 17499,
        "mrp": 22999,
        "costPrice": 6900,
        "badge": "Classic",
        "image": "/images/mens_bomber_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Lambskin Leather (1.1mm), Heavy Gauge Wool-Blend Ribbing",
        "fit": "Classic Relaxed Bomber Silhouette with blouson volume."
    },
    {
        "id": "prod_mb_a2_brown",
        "slug": "mens-a2-bourbon-aviator-flight-jacket-shearling-brown",
        "title": "A-2 Bourbon Aviator Flight Jacket with Shearling Collar",
        "subtitle": "1.3mm Heavyweight Bourbon Cowhide • Detachable Australian Shearling Collar",
        "shortDescription": "Authentic A-2 aviator flight jacket in rich bourbon cowhide with a detachable plush shearling collar.",
        "description": "Built for high altitudes and harsh winters. Made from 1.3mm bourbon cowhide with a detachable cream Australian shearling collar. Features twin dual-entry cargo flap pockets, ribbed hem and cuffs, and antique brass storm flap.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_men_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_bombers_flight", "col_new_arrivals"],
        "tags": ["leather", "aviator", "shearling", "bomber", "men", "brown", "bourbon"],
        "price": 21999,
        "mrp": 28999,
        "costPrice": 9200,
        "badge": "Winter Masterpiece",
        "image": "/images/mens_bomber_brown.jpg",
        "color": "Bourbon Brown",
        "colorHex": "#6E4120",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Vegetable-Tanned Cowhide (1.3mm), Genuine Australian Shearling Collar, Quilted Thermal Lining",
        "fit": "Generous Aviator Fit with gusseted back."
    },
    {
        "id": "prod_mb_ma1_red",
        "slug": "mens-oxblood-red-minimalist-zip-up-leather-bomber",
        "title": "Oxblood Red Minimalist Zip-Up Leather Bomber",
        "subtitle": "Supple Crimson Calfskin • Seamless Shoulders & Gunmetal Hardware",
        "shortDescription": "Modern minimalist bomber jacket in drum-dyed oxblood red leather with low-profile tonal ribbing.",
        "description": "Streamlined urban styling. Cut from supple crimson calfskin with tonal ribbed knit trim. Features gunmetal center zip, clean welt hand pockets, and an unpadded tailored fit ideal for year-round layering.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_men_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_bombers_flight"],
        "tags": ["leather", "bomber", "men", "red", "oxblood", "minimalist"],
        "price": 17999,
        "mrp": 23499,
        "costPrice": 7100,
        "badge": "Modern Cut",
        "image": "/images/mens_bomber_red.jpg",
        "color": "Oxblood Red",
        "colorHex": "#641920",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Calfskin Leather (1.0mm), Cotton Twill Lining",
        "fit": "Slim Modern Bomber Cut."
    },

    # 7. Women's Bomber / Flight Jackets (Black, Brown, Red)
    {
        "id": "prod_wb_ma1_black",
        "slug": "womens-cropped-ma1-leather-bomber-black",
        "title": "Cropped MA-1 Leather Bomber Jacket in Jet Black",
        "subtitle": "Butter-Soft Black Goat Nappa • Solid Gold Hardware & Knit Cuffs",
        "shortDescription": "Feminine cropped MA-1 leather bomber in jet black goat nappa with gold-tone hardware and ribbed waist.",
        "description": "Casual luxury with streetwear heritage. Cropped high at the waist with soft ribbed collar, cuffs, and hem. Features polished gold YKK zippers and butter-soft black goat nappa leather.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_women_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_bombers_flight"],
        "tags": ["leather", "bomber", "women", "black", "cropped", "gold_hardware"],
        "price": 16999,
        "mrp": 21999,
        "costPrice": 6700,
        "badge": "Bestseller",
        "image": "/images/womens_bomber_black.jpg",
        "color": "Jet Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Goat Nappa Leather (0.9mm), Stretch Knit Ribbing",
        "fit": "Cropped Relaxed Bomber Silhouette."
    },
    {
        "id": "prod_wb_aviator_brown",
        "slug": "womens-honey-tan-suede-aviator-bomber-shearling",
        "title": "Honey Tan Suede Aviator Bomber Jacket",
        "subtitle": "Plush Calf Suede • Shearling Lapel Trim & Antique Brass Zippers",
        "shortDescription": "Cozy honey tan calf suede aviator bomber with cream shearling collar trim and brass accents.",
        "description": "Ultra-soft velvety calf suede in golden honey tan. Finished with a cozy cream shearling collar trim, dual buckle side tabs, and antique brass zips.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_women_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_bombers_flight"],
        "tags": ["leather", "suede", "aviator", "bomber", "women", "brown", "tan"],
        "price": 18499,
        "mrp": 24499,
        "costPrice": 7500,
        "badge": "Winter Soft",
        "image": "/images/womens_bomber_brown.jpg",
        "color": "Honey Tan",
        "colorHex": "#C89650",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Velvety Calf Suede (1.0mm), Genuine Shearling Trim, Quilted Interior",
        "fit": "Relaxed Aviator Fit."
    },
    {
        "id": "prod_wb_ribbed_red",
        "slug": "womens-crimson-red-soft-leather-ribbed-bomber",
        "title": "Crimson Red Butter-Soft Leather Ribbed Bomber",
        "subtitle": "Drum-Dyed Crimson Lambskin • Charcoal Wool-Blend Ribbing",
        "shortDescription": "Vibrant crimson red soft leather bomber jacket featuring contrasting charcoal wool ribbed trims.",
        "description": "Vibrant and chic. Made from drum-dyed red lambskin that drapes effortlessly. Accented by contrasting charcoal grey wool-blend ribbed trims and silver metallic hardware.",
        "productType": "bomber",
        "categoryId": "cat_bombers",
        "categoryAncestry": ["cat_women_leather", "cat_bombers"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_bombers_flight"],
        "tags": ["leather", "bomber", "women", "red", "crimson", "ribbed"],
        "price": 17499,
        "mrp": 22999,
        "costPrice": 6900,
        "badge": "Pop Color",
        "image": "/images/womens_bomber_red.jpg",
        "color": "Crimson Red",
        "colorHex": "#8C1E28",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Glove-Soft Lambskin (0.9mm), Wool Ribbed Trim",
        "fit": "Tailored Feminine Bomber Cut."
    },

    # 8. Men's Café Racer Jackets (Black, Brown, Red)
    {
        "id": "prod_mr_racer_black",
        "slug": "mens-classic-mandarin-collar-black-cafe-racer",
        "title": "Classic Mandarin Snap Collar Black Café Racer Jacket",
        "subtitle": "1.2mm Full-Grain Buffalo Nappa • Dual Vertical Racing Chest Zips",
        "shortDescription": "Purist motorcycle café racer in black full-grain leather with a mandarin snap collar and streamlined racing cut.",
        "description": "The quintessential rider silhouette. Stripped of excess for clean aerodynamics. Features a snap-tab mandarin collar, straight vertical center zip, twin zippered chest pockets, and zippered wrist gussets.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers"],
        "tags": ["leather", "racer", "cafe_racer", "men", "black", "mandarin_collar"],
        "price": 18499,
        "mrp": 24499,
        "costPrice": 7500,
        "badge": "Racer Heritage",
        "image": "/images/mens_racer_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Buffalo Nappa (1.2mm), Heavy Cotton Twill Lining",
        "fit": "Athletic Slim Rider Fit."
    },
    {
        "id": "prod_mr_racer_brown",
        "slug": "mens-antique-tan-quilted-shoulder-cafe-racer",
        "title": "Antique Tan Quilted Shoulder Café Racer Jacket",
        "subtitle": "Hand-Waxed Antique Tan Cowhide • Diamond Shoulder Quilting",
        "shortDescription": "Vintage hand-waxed antique tan leather café racer featuring diamond-quilted shoulders and brass zips.",
        "description": "Rich in character and old-school charm. Hand-waxed cowhide leather in warm antique tan. Features diamond quilting across the shoulders and elbows, mandarin snap neck, and brass zip hardware.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers", "col_bestsellers"],
        "tags": ["leather", "racer", "brown", "tan", "quilted", "men", "bestseller"],
        "price": 19299,
        "mrp": 25499,
        "costPrice": 7900,
        "badge": "Bestseller",
        "image": "/images/mens_racer_brown.jpg",
        "color": "Antique Tan",
        "colorHex": "#8C461E",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Hand-Waxed Cowhide Leather (1.2mm), Plaid Cotton Lining",
        "fit": "Tailored Café Racer Fit with gusseted movement."
    },
    {
        "id": "prod_mr_racer_red",
        "slug": "mens-oxblood-track-racing-leather-jacket-red",
        "title": "Oxblood Track Racing Leather Jacket with Ivory Stripes",
        "subtitle": "Drum-Dyed Crimson Lambskin • Contrast Racing Sleeve Stripes",
        "shortDescription": "Track-inspired café racer in oxblood red leather accented with dual ivory sleeve racing stripes.",
        "description": "Motorsport adrenaline meets luxury leather. Oxblood red lambskin with contrast off-white racing stripes stitched along both sleeves. Equipped with mandarin snap collar, perforated underarm vents, and chest zips.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection", "col_biker_racers"],
        "tags": ["leather", "racer", "track", "men", "red", "oxblood", "stripes"],
        "price": 19999,
        "mrp": 26499,
        "costPrice": 8300,
        "badge": "Track Edition",
        "image": "/images/mens_racer_red.jpg",
        "color": "Oxblood Red",
        "colorHex": "#641920",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Lambskin (1.1mm), Breathable Mesh Lining",
        "fit": "Sport Slim Fit."
    },

    # 9. Women's Café Racer Jackets (Black, Brown, Red)
    {
        "id": "prod_wr_racer_black",
        "slug": "womens-band-collar-slim-black-leather-cafe-racer",
        "title": "Band-Collar Slim Black Leather Café Racer",
        "subtitle": "Ultra-Fine Grain Black Lambskin • Minimalist Silver Hardware",
        "shortDescription": "Minimalist women's black leather café racer with a neat band collar and tailored vertical seamlines.",
        "description": "Sleek, architectural, and effortlessly cool. Tailored with princess seam paneling from ultra-fine grain black lambskin. Features a minimal snap-band collar, exposed silver center zipper, and zippered hand pockets.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers"],
        "tags": ["leather", "racer", "women", "black", "slim", "minimalist"],
        "price": 17499,
        "mrp": 22999,
        "costPrice": 7000,
        "badge": "Essential",
        "image": "/images/womens_racer_black.jpg",
        "color": "Jet Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Ultra-Fine Lambskin Nappa (0.9mm), Stretch Silk Lining",
        "fit": "Slim Form-Fitting Silhouette."
    },
    {
        "id": "prod_wr_racer_brown",
        "slug": "womens-honey-cognac-vintage-leather-racer",
        "title": "Honey Cognac Vintage Leather Café Racer",
        "subtitle": "Vegetable-Tanned Goat Leather • Antique Patina & Zippered Cuffs",
        "shortDescription": "Vintage-inspired women's café racer in honey cognac leather with subtle natural pull-up shading.",
        "description": "A timeless wardrobe investment. Made from vegetable-tanned goat leather that softens with every wear. Finished with antique brass zips, snap collar tab, and tailored side gussets.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers"],
        "tags": ["leather", "racer", "women", "brown", "cognac", "vintage"],
        "price": 17999,
        "mrp": 23499,
        "costPrice": 7200,
        "badge": "Artisan Favorite",
        "image": "/images/womens_racer_brown.jpg",
        "color": "Honey Cognac",
        "colorHex": "#A86632",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Vegetable-Tanned Goat Leather (0.9mm), Viscose Twill Lining",
        "fit": "Contoured Slim Fit."
    },
    {
        "id": "prod_wr_racer_red",
        "slug": "womens-ruby-red-mandarin-collar-slim-racer",
        "title": "Ruby Red Mandarin Collar Slim Leather Racer",
        "subtitle": "Drum-Dyed Ruby Wine Lambskin • Clean Minimal Lines & Zip Pockets",
        "shortDescription": "Sophisticated ruby wine red leather café racer tailored with a snap-fastened band collar.",
        "description": "Rich gemstone hues in butter-soft lambskin. Cut with flattering vertical lines, mandarin snap collar, and sleek silver zip hardware.",
        "productType": "racer",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection", "col_biker_racers"],
        "tags": ["leather", "racer", "women", "red", "ruby", "wine"],
        "price": 18499,
        "mrp": 24299,
        "costPrice": 7400,
        "badge": "Statement",
        "image": "/images/womens_racer_red.jpg",
        "color": "Ruby Red",
        "colorHex": "#781822",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Lambskin (0.9mm), Satin Lining",
        "fit": "Tailored Slim Fit."
    },

    # 10. Men's Trucker Jackets (Black, Brown, Red)
    {
        "id": "prod_mt_trucker_black",
        "slug": "mens-western-cut-black-leather-trucker-jacket",
        "title": "Western-Cut Full-Grain Black Leather Trucker Jacket",
        "subtitle": "1.1mm Cowhide • Point Collar, Flap Chest Pockets & Nickel Shank Buttons",
        "shortDescription": "Classic Type III western trucker jacket tailored from heavy-duty full-grain black cowhide with metal shank buttons.",
        "description": "The American western denim silhouette elevated with heavy 1.1mm full-grain black cowhide. Features dual buttoned flap chest pockets, vertical seam panels, welt hand pockets, side waist tabs, and solid nickel shank buttons.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection"],
        "tags": ["leather", "trucker", "western", "men", "black", "jacket"],
        "price": 17999,
        "mrp": 23999,
        "costPrice": 7300,
        "badge": "Rugged Classic",
        "image": "/images/mens_trucker_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Full-Grain Cowhide Leather (1.1mm), Unlined Body with Satin Sleeve Lining",
        "fit": "Classic Boxy Western Trucker Cut. Hits at hip."
    },
    {
        "id": "prod_mt_trucker_brown",
        "slug": "mens-tobacco-roughout-suede-western-trucker-jacket",
        "title": "Tobacco Roughout Suede Western Trucker Jacket",
        "subtitle": "Heavyweight Tobacco Suede • Antique Brass Shanks & Contrast Stitching",
        "shortDescription": "Heritage western trucker jacket in rich tobacco roughout suede leather with antique brass button closure.",
        "description": "Rugged, textured, and deeply tactile. Crafted from heavy tobacco roughout suede with double-stitched yoke panels. Features pointed flap chest pockets, welt hand pockets, and antique brass shank buttons.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection"],
        "tags": ["leather", "suede", "trucker", "western", "men", "brown", "tobacco"],
        "price": 18999,
        "mrp": 24999,
        "costPrice": 7800,
        "badge": "Heritage Suede",
        "image": "/images/mens_trucker_brown.jpg",
        "color": "Tobacco Brown",
        "colorHex": "#7D4B26",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Heavy Roughout Suede Leather (1.2mm), Chambray Pocket Bags",
        "fit": "Straight Western Cut."
    },
    {
        "id": "prod_mt_trucker_red",
        "slug": "mens-rust-burgundy-leather-western-trucker-jacket",
        "title": "Rust Burgundy Leather Western Trucker Jacket",
        "subtitle": "Drum-Dyed Burgundy Calf Leather • Contrast Stitching & Gunmetal Hardware",
        "shortDescription": "Unique rust burgundy leather western trucker jacket with tonal seam detailing and shank button front.",
        "description": "Rich autumnal tones meet iconic trucker styling. Cut from drum-dyed burgundy calfskin with natural grain. Finished with pointed pocket flaps, welt pockets, and gunmetal hardware.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_men_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_mens_collection"],
        "tags": ["leather", "trucker", "men", "red", "burgundy", "rust"],
        "price": 18499,
        "mrp": 24499,
        "costPrice": 7500,
        "badge": "Autumn Edit",
        "image": "/images/mens_trucker_red.jpg",
        "color": "Rust Red",
        "colorHex": "#731E26",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "genderScope": "Men",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Calfskin (1.1mm), Cotton Lining",
        "fit": "Classic Regular Trucker Fit."
    },

    # 11. Women's Trucker Jackets (Black, Brown, Red)
    {
        "id": "prod_wt_trucker_black",
        "slug": "womens-cropped-western-black-leather-trucker",
        "title": "Cropped Western Black Leather Trucker Jacket",
        "subtitle": "Supple Black Lambskin • Silver Shank Buttons & Flap Pockets",
        "shortDescription": "Women's cropped leather trucker jacket in soft black lambskin with silver shank buttons and clean chest flaps.",
        "description": "The rugged trucker reimagined with feminine proportions. Cropped length with tailored shoulders and waist tabs. Crafted from glove-soft black lambskin with polished silver shank buttons.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection"],
        "tags": ["leather", "trucker", "women", "black", "cropped", "western"],
        "price": 16999,
        "mrp": 22499,
        "costPrice": 6800,
        "badge": "Trending",
        "image": "/images/womens_trucker_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Supple Lambskin Leather (0.9mm), Viscose Lining",
        "fit": "Cropped Feminine Trucker Fit."
    },
    {
        "id": "prod_wt_trucker_brown",
        "slug": "womens-warm-cognac-leather-trucker-jacket",
        "title": "Warm Cognac Leather Western Trucker Jacket",
        "subtitle": "Vegetable-Tanned Cognac Leather • Antique Brass Shanks & Chest Pockets",
        "shortDescription": "Warm cognac tan leather trucker jacket with antique brass buttons and tailored point collar.",
        "description": "Rich honey cognac leather tailored in a sharp western silhouette. Features dual pointed chest flaps, vertical topstitched panels, and antique brass buttons.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection"],
        "tags": ["leather", "trucker", "women", "brown", "cognac", "western"],
        "price": 17499,
        "mrp": 22999,
        "costPrice": 7100,
        "badge": "Classic",
        "image": "/images/womens_trucker_brown.jpg",
        "color": "Cognac Brown",
        "colorHex": "#A86632",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Vegetable-Tanned Goat Leather (0.9mm), Satin Lining",
        "fit": "Tailored Western Fit."
    },
    {
        "id": "prod_wt_trucker_red",
        "slug": "womens-dark-cherry-red-leather-western-trucker",
        "title": "Dark Cherry Red Leather Western Trucker Jacket",
        "subtitle": "Crimson Lambskin • Gunmetal Buttons & Contoured Yoke",
        "shortDescription": "Dark cherry red leather trucker jacket featuring tailored western yoke lines and gunmetal shank buttons.",
        "description": "Deep crimson hues in butter-soft lambskin. Pointed western chest pockets, buttoned cuffs, and adjustable side waist tabs.",
        "productType": "trucker",
        "categoryId": "cat_jackets",
        "categoryAncestry": ["cat_women_leather", "cat_jackets"],
        "collectionIds": ["col_all_leather", "col_womens_collection"],
        "tags": ["leather", "trucker", "women", "red", "cherry", "western"],
        "price": 17999,
        "mrp": 23499,
        "costPrice": 7300,
        "badge": "Autumn Edit",
        "image": "/images/womens_trucker_red.jpg",
        "color": "Dark Cherry Red",
        "colorHex": "#6E1C26",
        "sizes": ["XS", "S", "M", "L", "XL"],
        "genderScope": "Women",
        "hsnCode": "42031010",
        "gstRate": 12,
        "fabric": "100% Drum-Dyed Lambskin (0.9mm), Silk Twill Lining",
        "fit": "Tailored Slim Trucker Cut."
    },

    # 12. Leather Goods & Accessories
    {
        "id": "prod_lg_duffel",
        "slug": "the-voyager-45l-full-grain-leather-weekend-duffle",
        "title": "The Voyager 45L Full-Grain Leather Weekend Duffle",
        "subtitle": "Obsidian & Bourbon Full-Grain Cowhide • Solid Brass Hardware & YKK Zippers",
        "shortDescription": "Cabin-approved 45L travel duffel bag handcrafted from full-grain black and bourbon leather with solid brass hardware.",
        "description": "Handcrafted for a lifetime of journeys. Cut from 1.8mm full-grain cowhide reinforced at stress points with solid copper rivets. Features rolled leather carry handles, detachable padded shoulder strap, shoe compartment, and heavy-duty double YKK brass zippers.",
        "productType": "accessory",
        "categoryId": "cat_accessories",
        "categoryAncestry": ["cat_accessories"],
        "collectionIds": ["col_all_leather", "col_bestsellers", "col_new_arrivals"],
        "tags": ["leather", "bag", "duffle", "travel", "weekend", "accessories", "bestseller"],
        "price": 14999,
        "mrp": 19999,
        "costPrice": 5900,
        "badge": "Bestseller",
        "image": "/images/leather_weekend_duffel.jpg",
        "color": "Black & Bourbon Tan",
        "colorHex": "#18201B",
        "sizes": ["One Size (45L)"],
        "genderScope": "Unisex",
        "hsnCode": "42021110",
        "gstRate": 18,
        "fabric": "100% Full-Grain Vegetable-Tanned Cowhide (1.8mm), Waterproof Cotton Twill Lining, Solid Brass Hardware",
        "fit": "Cabin Approved (52cm L x 28cm W x 28cm H • 45 Litre Capacity)."
    },
    {
        "id": "prod_lg_briefcase",
        "slug": "the-artisan-commuter-vegetable-tanned-leather-briefcase",
        "title": "The Artisan Commuter Vegetable-Tanned Leather Briefcase",
        "subtitle": "Saddle Cognac Leather • Padded 16-Inch Laptop Sleeve & Brass Tuck Buckles",
        "shortDescription": "Hand-stitched vegetable-tanned leather briefcase with a padded 16-inch laptop divider and organizer pockets.",
        "description": "The definitive business briefcase. Structured saddle cognac leather with dual brass tuck buckle closures. Inside features a padded compartment for up to a 16-inch laptop, tablet sleeve, pen slots, and luggage trolley strap.",
        "productType": "accessory",
        "categoryId": "cat_accessories",
        "categoryAncestry": ["cat_accessories"],
        "collectionIds": ["col_all_leather"],
        "tags": ["leather", "briefcase", "bag", "laptop", "office", "accessories"],
        "price": 12999,
        "mrp": 16999,
        "costPrice": 5200,
        "badge": "Artisan Edit",
        "image": "/images/leather_commuter_briefcase.jpg",
        "color": "Saddle Cognac",
        "colorHex": "#915528",
        "sizes": ["One Size (15L)"],
        "genderScope": "Unisex",
        "hsnCode": "42021110",
        "gstRate": 18,
        "fabric": "100% Vegetable-Tanned Full-Grain Cowhide (1.6mm), Padded Microfiber Lining",
        "fit": "Fits 13-inch to 16-inch Laptops (41cm W x 30cm H x 10cm D)."
    },
    {
        "id": "prod_fw_chelsea_black",
        "slug": "goodyear-welted-calfskin-chelsea-boots-black",
        "title": "Goodyear-Welted Calfskin Chelsea Boots in Obsidian Black",
        "subtitle": "Box Calf Black Leather • Goodyear-Welted Stacked Leather Sole & Cork Insole",
        "shortDescription": "Handcrafted black calfskin Chelsea boots with Goodyear-welted construction and natural crepe rubber traction grip.",
        "description": "Master shoemaking from Kolhapur guild artisans. Built from smooth box calf black leather on classic lasts. Goodyear-welted stacked leather sole with inset crepe rubber grip and moisture-wicking calfskin lining.",
        "productType": "footwear",
        "categoryId": "cat_footwear",
        "categoryAncestry": ["cat_footwear"],
        "collectionIds": ["col_all_leather", "col_new_arrivals"],
        "tags": ["leather", "boots", "chelsea", "footwear", "men", "goodyear_welt"],
        "price": 11999,
        "mrp": 15999,
        "costPrice": 4900,
        "badge": "Handcrafted",
        "image": "/images/leather_chelsea_boots_black.jpg",
        "color": "Obsidian Black",
        "colorHex": "#18201B",
        "sizes": ["UK 7", "UK 8", "UK 9", "UK 10", "UK 11"],
        "genderScope": "Unisex",
        "hsnCode": "64035111",
        "gstRate": 18,
        "fabric": "100% Box Calf Leather Upper, Calfskin Lining, Goodyear-Welted Leather & Rubber Sole",
        "fit": "True to UK/India Shoe Size with cushioned arch support."
    },
    {
        "id": "prod_lg_belt_bourbon",
        "slug": "heritage-brass-buckle-bridle-leather-belt-bourbon",
        "title": "Heritage 1.5\" Full-Grain Brass-Buckle Leather Belt",
        "subtitle": "4mm Heavy Saddle Bourbon Bridle Leather • Solid Sandcast Brass Buckle",
        "shortDescription": "Indestructible 1.5-inch wide belt crafted from 4mm thick bourbon bridle leather with a solid sandcast brass buckle.",
        "description": "Cut from a single strip of 4mm thick vegetable-tanned bridle leather with burnished beveled edges. Fitted with a heavy solid sandcast brass buckle fastened by screw-post rivets.",
        "productType": "accessory",
        "categoryId": "cat_accessories",
        "categoryAncestry": ["cat_accessories"],
        "collectionIds": ["col_all_leather"],
        "tags": ["leather", "belt", "accessories", "bourbon", "brass"],
        "price": 2499,
        "mrp": 3299,
        "costPrice": 950,
        "badge": "Lifetime Leather",
        "image": "/images/leather_dress_belt_bourbon.jpg",
        "color": "Bourbon Tan",
        "colorHex": "#9B5A2A",
        "sizes": ["30", "32", "34", "36", "38", "40"],
        "genderScope": "Unisex",
        "hsnCode": "42033000",
        "gstRate": 18,
        "fabric": "100% Heavy Bridle Leather (4.0mm), Solid Sandcast Brass Buckle",
        "fit": "Order 2 inches up from your pant waist size (e.g. Size 34 for 32 Pant)."
    }
]

# Build variants array for each product
def build_variants(p):
    variants = []
    sizes = p["sizes"]
    base_price = p["price"]
    mrp = p["mrp"]
    cost = p["costPrice"]
    color = p["color"]
    color_hex = p["colorHex"]
    img = p["image"]
    pid = p["id"]
    
    for i, s in enumerate(sizes):
        clean_s = s.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_").lower()
        vid = f"var_{pid}_{clean_s}"
        sku = f"KRG-LTH-{pid.replace('prod_', '').upper()}-{clean_s.upper()}"
        barcode = f"8904123{abs(hash(vid)) % 1000000:06d}"
        variants.append({
            "id": vid,
            "sku": sku,
            "barcode": barcode,
            "size": s,
            "color": color,
            "colorHex": color_hex,
            "material": p["fabric"].split(",")[0],
            "price": base_price,
            "mrp": mrp,
            "costPrice": cost,
            "weightGrams": 1400 if "coat" in pid else 1100 if "jacket" in pid or "racer" in pid or "trucker" in pid or "bomber" in pid else 550 if "skirt" in pid else 1800 if "duffel" in pid else 950,
            "image": img,
            "onHand": 12 + (i * 3),
            "reserved": 0,
            "allocated": 1 if i == 1 else 0,
            "unavailable": 0,
            "incoming": 10,
            "lowStockThreshold": 3,
            "enabled": True
        })
    return variants

# Format full initialProducts array
products_code_blocks = []
for p in PRODUCTS:
    vars_list = build_variants(p)
    prod_obj = {
        "id": p["id"],
        "slug": p["slug"],
        "title": p["title"],
        "subtitle": p["subtitle"],
        "shortDescription": p["shortDescription"],
        "description": p["description"],
        "productType": p["productType"],
        "brand": "Karigar & Co.",
        "supplierId": "sup_kolhapur_guild",
        "categoryId": p["categoryId"],
        "categoryAncestry": p["categoryAncestry"],
        "collectionIds": p["collectionIds"],
        "tags": p["tags"],
        "status": "published",
        "price": p["price"],
        "mrp": p["mrp"],
        "costPrice": p["costPrice"],
        "badge": p["badge"],
        "images": [{"id": f"img_{p['id']}_1", "url": p["image"], "alt": p["title"], "focalPoint": {"x": 0.5, "y": 0.5}}],
        "variants": vars_list,
        "attributes": {
            "fabric": p["fabric"],
            "fit": p["fit"],
            "weaveOrConstruction": "Precision bench-crafted with bonded nylon thread and heavy YKK hardware",
            "careInstructions": "Professional leather clean only. Store on wide wooden hanger in breathable cotton dust bag.",
            "packageContents": f"1 {p['title']} + 1 Heavy Canvas Garment Bag + 1 Leather Care Cream Tin",
            "occasion": "Everyday Luxury, Evening Travel, Moto & Satorial Styling",
            "genderScope": p["genderScope"],
            "sizeSystem": "Standard Indian / International Apparel Sizing",
            "dimensionsCm": "60 x 45 x 8 cm",
        },
        "legalMetrology": {
            "genericName": f"{p['genderScope']} Handcrafted Leather {p['productType'].capitalize()}",
            "manufacturerName": "Karigar Everyday Apparel & Goods Pvt. Ltd.",
            "manufacturerAddress": "Plot 42, Industrial Estate, Lower Parel, Mumbai, Maharashtra 400013",
            "packerName": "Karigar Studio Fulfilment Centre, Indiranagar, Bengaluru 560038",
            "countryOfOrigin": "India",
            "netQuantity": "1 N",
            "consumerCareEmail": "care@karigarstore.in",
            "consumerCarePhone": "+91 80 4123 9876",
            "hsnCode": p["hsnCode"],
            "gstRatePercent": p["gstRate"],
        },
        "returnPolicyClass": "7_day_easy_return",
        "returnWindowDays": 7,
        "warrantySummary": "5-Year Leather Seams, Hardware & YKK Zipper Guarantee.",
        "seo": {
            "title": f"{p['title']} | Karigar & Co. Leather Atelier",
            "description": p["shortDescription"],
            "canonicalSlug": p["slug"],
            "noindex": False
        },
        "relatedProductIds": ["prod_lg_duffel", "prod_lg_belt_bourbon", "prod_fw_chelsea_black"],
        "goesWellWithIds": ["prod_lg_duffel", "prod_lg_belt_bourbon"],
        "ratingAverage": 4.9,
        "ratingCount": 36,
        "reviewCount": 14,
        "createdAt": "2026-08-01T10:00:00+05:30",
        "updatedAt": "2026-09-28T12:00:00+05:30",
        "revision": 2,
        "history": [
            {
                "revision": 1,
                "actor": "system_seed",
                "timestamp": "2026-08-01T10:00:00+05:30",
                "summary": "Initial leather atelier catalogue creation"
            },
            {
                "revision": 2,
                "actor": "superadmin@store.com",
                "timestamp": "2026-09-28T12:00:00+05:30",
                "summary": "Updated AW26 leather specifications & pricing"
            }
        ]
    }
    products_code_blocks.append(prod_obj)

print(f"Generated {len(products_code_blocks)} leather products!")

# Write complete seed.ts
with open("src/lib/seed.ts", "w", encoding="utf-8") as f:
    from generate_all_seed_products import get_all_products_code
    f.write(get_all_products_code())
    f.write("\nexport const initialProducts: ProductRecord[] = " + json.dumps(products_code_blocks, indent=2) + ";\n")
    
    # CMS Sections (13 sections tailored to leather brand)
    cms_sections = [
        {
            "id": "sec_hero_1",
            "type": "hero_campaign",
            "friendlyName": "01. Hero Campaign — Leather for Everyday Living",
            "enabled": True,
            "order": 1,
            "revision": 3,
            "eyebrow": "LEATHER CLOTHING FOR MEN & WOMEN",
            "heading": "Leather for Everyday Living",
            "subheading": "Full-grain leather jackets, coats and skirts for men and women. Find your fit.",
            "desktopImage": "/images/hero-desktop.jpg",
            "mobileImage": "/images/hero-mobile.jpg",
            "imageAlt": "Two models wearing a black leather biker jacket and a brown leather coat",
            "primaryCtaLabel": "Shop Men",
            "primaryCtaHref": "/category/men-leather",
            "secondaryCtaLabel": "Shop Women",
            "secondaryCtaHref": "/category/women-leather",
            "proofLine": "Size exchange within 7 days • Prices include GST",
            "backgroundTone": "ivory",
            "startsAt": "2026-01-01T00:00:00+05:30",
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_categories_2",
            "type": "category_shortcuts",
            "friendlyName": "02. Shop by Category",
            "enabled": True,
            "order": 2,
            "revision": 3,
            "eyebrow": "",
            "heading": "Shop by Category",
            "subheading": "",
            "categoryIds": ["cat_jackets", "cat_coats", "cat_bombers", "cat_skirts", "cat_accessories", "cat_footwear"],
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_store_picks_3",
            "type": "product_grid",
            "friendlyName": "03. Signature Biker & Moto Collection",
            "enabled": True,
            "order": 3,
            "revision": 2,
            "eyebrow": "SIGNATURE BIKER & RACER ICONS",
            "heading": "The Core Leather Icons",
            "subheading": "Heavy-duty YKK hardware, 1.1mm full-grain lambskin, and ergonomic quilted shoulders.",
            "productIds": ["prod_mj_biker_black", "prod_wj_biker_black", "prod_mr_racer_brown", "prod_mj_biker_red"],
            "primaryCtaLabel": "View All Jackets",
            "primaryCtaHref": "/category/jackets",
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_story_origin_4",
            "type": "story_split",
            "friendlyName": "04. Story 1 — Why the Store Started",
            "enabled": True,
            "order": 4,
            "revision": 2,
            "eyebrow": "ORIGIN STORY • SINCE 2019",
            "heading": "Why We Built an Uncompromising Leather Atelier",
            "description": "Commercial fast-fashion leather jackets peel after two seasons because they use bonded synthetic scraps coated in polyurethane. We founded Karigar in 2019 to return to authentic bench-crafting: full-grain drum-dyed hides, heavy cotton linings, solid brass hardware, and hand-finished edges that look better with every mile.",
            "desktopImage": "/images/story-workshop.jpg",
            "mobileImage": "/images/story-workshop.jpg",
            "imageAlt": "Master leather craftsman inspecting hides at the cutting table",
            "primaryCtaLabel": "Read Our Full Origin Story",
            "primaryCtaHref": "/story",
            "proofLine": "Every hide hand-selected and grain-inspected before pattern cutting",
            "facts": [
                {"title": "1.1–1.3mm Hides", "body": "Drum-dyed full-grain lambskin, cowhide & goat nappa."},
                {"title": "YKK Heavy Hardware", "body": "Solid brass and nickel-free heavy-duty metal zippers."},
                {"title": "5-Year Guarantee", "body": "Free seam, hardware, and zipper repair for 5 years."}
            ],
            "backgroundTone": "ivory_subtle",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_story_products_5",
            "type": "product_rail",
            "friendlyName": "05. Tailored Longline Leather Coats",
            "enabled": True,
            "order": 5,
            "revision": 2,
            "eyebrow": "TAILORED LONGLINE DRAPE",
            "heading": "Leather Overcoats & Trench Coats",
            "subheading": "Double-breasted trench coats and tailored car coats crafted from supple full-grain hides.",
            "productIds": ["prod_mc_car_black", "prod_mc_trench_brown", "prod_wc_trench_black", "prod_wc_trench_brown"],
            "primaryCtaLabel": "Explore All Coats",
            "primaryCtaHref": "/category/coats",
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_story_people_6",
            "type": "story_people",
            "friendlyName": "06. Story 2 — Meet the People Behind the Craft",
            "enabled": True,
            "order": 6,
            "revision": 2,
            "eyebrow": "MASTER ARTISANS & PATTERN CUTTERS",
            "heading": "Crafted by Hands with Decades of Mastery",
            "description": "Behind every Karigar jacket is a small team of master pattern makers, leather skivers, and bench artisans across our Mumbai cutting room and Bengaluru studio. Each garment is assigned to an individual artisan from hide selection to final edge burnishing.",
            "desktopImage": "/images/story-founder.jpg",
            "mobileImage": "/images/story-founder.jpg",
            "imageAlt": "Master artisan examining a tailored leather jacket on mannequin",
            "primaryCtaLabel": "Meet Our Workshop Team",
            "primaryCtaHref": "/team",
            "proofLine": "Zero assembly lines. Tailored by master pattern cutters.",
            "facts": [
                {"title": "Bengaluru Studio", "body": "Indiranagar showroom, custom fitting and dispatch desk."},
                {"title": "Mumbai Cutting Room", "body": "Full-grain hide selection and precision pattern cutting."},
                {"title": "Kolhapur Guild", "body": "Goodyear-welted footwear and vegetable-tanned bridle leather."}
            ],
            "backgroundTone": "ivory_subtle",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_new_arrivals_7",
            "type": "product_grid",
            "friendlyName": "07. Bomber & Flight Jackets",
            "enabled": True,
            "order": 7,
            "revision": 2,
            "eyebrow": "AVIATOR & MILITARY HERITAGE",
            "heading": "Bomber & Flight Jackets",
            "subheading": "MA-1 lambskin flight bombers and A-2 shearling collar aviator jackets.",
            "productIds": ["prod_mb_ma1_black", "prod_mb_a2_brown", "prod_wb_ma1_black", "prod_wb_aviator_brown"],
            "primaryCtaLabel": "View All Bombers",
            "primaryCtaHref": "/category/bombers",
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_story_craft_8",
            "type": "story_craft",
            "friendlyName": "08. Story 3 — What Makes the Leather Different",
            "enabled": True,
            "order": 8,
            "revision": 2,
            "eyebrow": "THE KARIGAR LEATHER STANDARD",
            "heading": "Vegetable Tanning, Heavy Hardware & Precision Seams",
            "description": "We source top-tier drum-dyed full-grain hides tanned with natural bark extracts and essential oils. The leather breathes, softens, and develops rich depth without cracking. We reinforce stress points with bonded nylon thread and double-stitched felled seams.",
            "desktopImage": "/images/story-craft.jpg",
            "mobileImage": "/images/story-craft.jpg",
            "imageAlt": "Macro detail of saddle stitching and heavy YKK brass zipper",
            "primaryCtaLabel": "Learn About Our Leather Grades",
            "primaryCtaHref": "/story",
            "proofLine": "Every hide inspected under 5000K daylight simulation",
            "facts": [
                {"title": "Full-Grain Only", "body": "Never corrected, sanded, or split-bonded leather."},
                {"title": "Bonded Nylon Stitching", "body": "Heavy-gauge industrial thread that never rots or frays."},
                {"title": "Breathable Linings", "body": "Viscose satin and Bemberg cupro for all-day comfort."}
            ],
            "backgroundTone": "ivory_subtle",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_reviews_9",
            "type": "reviews_service",
            "friendlyName": "09. Customer Reviews & Service Assurances",
            "enabled": True,
            "order": 9,
            "revision": 2,
            "eyebrow": "VERIFIED CUSTOMER EXPERIENCES",
            "heading": "Worn, Tested & Trusted Across India",
            "subheading": "4.9 / 5 average rating across 650+ verified leather jacket and bag owners.",
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_offer_10",
            "type": "campaign_offer",
            "friendlyName": "10. Atelier Wardrobe Promotion Banner",
            "enabled": True,
            "order": 10,
            "revision": 2,
            "eyebrow": "SEASONAL ATELIER INCENTIVE",
            "heading": "Flat ₹500 Off When You Order Two Leather Pieces",
            "description": "Combine any leather jacket with a skirt, duffle bag, or boots and get an immediate ₹500 discount on your bag total.",
            "offerCode": "FESTIVE500",
            "offerConditions": "Applies automatically on checkout orders of ₹2,500 and above. Combinable with Free Insured Delivery.",
            "primaryCtaLabel": "Shop Signature Collection",
            "primaryCtaHref": "/collection/all-leather",
            "backgroundTone": "gold_tint",
            "startsAt": "2026-09-01T00:00:00+05:30",
            "endsAt": "2026-12-31T23:59:59+05:30",
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_need_11",
            "type": "shop_by_need",
            "friendlyName": "11. Shop by Style or Requirement",
            "enabled": True,
            "order": 11,
            "revision": 2,
            "eyebrow": "CURATED EDITS",
            "heading": "Find Your Ideal Leather Silhouette",
            "subheading": "From daily urban commute to road trips and formal evenings.",
            "needCards": [
                {"title": "Motorcycle & Café Racers", "subtitle": "Ergonomic cuts & heavy zips", "href": "/collection/biker-and-racers", "image": "/images/cat-jackets.jpg", "alt": "Biker and racer jackets"},
                {"title": "Tailored Coats & Trench", "subtitle": "Belted longline silhouettes", "href": "/collection/coats-and-trench", "image": "/images/cat-coats.jpg", "alt": "Leather coats and trench"},
                {"title": "Women's Leather Skirts", "subtitle": "A-line, pencil & wrap styles", "href": "/category/skirts", "image": "/images/cat-skirts.jpg", "alt": "Women's leather skirts"},
                {"title": "Travel Bags & Weekend Duffels", "subtitle": "Full-grain 45L travel bags", "href": "/category/accessories", "image": "/images/cat-accessories.jpg", "alt": "Leather travel bags and goods"}
            ],
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_local_12",
            "type": "story_local_store",
            "friendlyName": "12. Story 4 — Indiranagar Studio & Touchpoints",
            "enabled": True,
            "order": 12,
            "revision": 2,
            "eyebrow": "VISIT OUR FLAGSHIP STUDIO",
            "heading": "Try In Person at Our Indiranagar Studio",
            "description": "Experience hide textures, try on sizes, and consult with our leather master in person. Located in the heart of Bengaluru.",
            "desktopImage": "/images/story-studio.jpg",
            "mobileImage": "/images/story-studio.jpg",
            "imageAlt": "Flagship leather studio in Indiranagar Bengaluru",
            "storeDetails": {
                "city": "Bengaluru, Karnataka",
                "neighbourhood": "Indiranagar (HAL 2nd Stage)",
                "address": "123, 12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038",
                "hours": "Monday to Saturday: 10:00 AM – 7:00 PM IST",
                "phone": "+91 80 4123 9876",
                "email": "care@karigarstore.in",
                "whatsapp": "+91 98765 43210",
                "pickupInfo": "Complimentary same-day studio pickup and custom sleeve length adjustments available.",
                "directionsUrl": "https://maps.google.com/?q=12th+Main+Road+Indiranagar+Bengaluru+560038"
            },
            "primaryCtaLabel": "Get Studio Directions",
            "primaryCtaHref": "/visit",
            "secondaryCtaLabel": "Contact Leather Desk",
            "secondaryCtaHref": "/contact",
            "backgroundTone": "ivory_subtle",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        },
        {
            "id": "sec_recommended_13",
            "type": "recently_viewed",
            "friendlyName": "13. Recently Viewed Leather Goods",
            "enabled": True,
            "order": 13,
            "revision": 2,
            "eyebrow": "CONTINUE EXPLORING",
            "heading": "Recently Viewed & Complementary Leather Pieces",
            "subheading": "Your local device browsing history paired with complementary atelier pieces.",
            "collectionId": "col_all_leather",
            "productIds": ["prod_mj_biker_black", "prod_wj_biker_black", "prod_lg_duffel", "prod_fw_chelsea_black"],
            "backgroundTone": "ivory",
            "startsAt": None,
            "endsAt": None,
            "timezone": "Asia/Kolkata"
        }
    ]
    f.write("\nexport const initialCMSSections: CMSSection[] = " + json.dumps(cms_sections, indent=2) + ";\n")
    
    # Releases, Pincodes, Orders, Reviews, Suppliers, Staff
    f.write("""
export const initialReleases: CMSReleaseManifest[] = [
  {
    id: 'rel_v1',
    versionNumber: 1,
    publishedAt: '2026-09-01T09:00:00+05:30',
    publishedBy: 'superadmin@store.com',
    releaseNote: 'Initial launch release with core leather catalogue.',
    sectionsSnapshot: initialCMSSections.slice(0, 8),
    globalSettingsSnapshot: initialGlobalSettings,
  },
  {
    id: 'rel_v2',
    versionNumber: 2,
    publishedAt: '2026-09-28T12:00:00+05:30',
    publishedBy: 'superadmin@store.com',
    releaseNote: 'Complete 13-section luxury leather fashion store release.',
    sectionsSnapshot: initialCMSSections,
    globalSettingsSnapshot: initialGlobalSettings,
  },
];

export const initialPincodes = [
  { pincode: '560038', city: 'Bengaluru', state: 'Karnataka', zone: 'Local Metro (Intra-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '1–2 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '560001', city: 'Bengaluru', state: 'Karnataka', zone: 'Local Metro (Intra-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '1–2 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '400001', city: 'Mumbai', state: 'Maharashtra', zone: 'West Metro (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '2–4 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '400013', city: 'Mumbai', state: 'Maharashtra', zone: 'West Metro (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '2–3 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '110001', city: 'New Delhi', state: 'Delhi', zone: 'North Metro (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '3–5 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '600001', city: 'Chennai', state: 'Tamil Nadu', zone: 'South Zone (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '2–3 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '500001', city: 'Hyderabad', state: 'Telangana', zone: 'South Zone (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '2–3 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '700001', city: 'Kolkata', state: 'West Bengal', zone: 'East Metro (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 12000, transitDays: '4–6 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '411001', city: 'Pune', state: 'Maharashtra', zone: 'West Zone (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '3–4 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '380001', city: 'Ahmedabad', state: 'Gujarat', zone: 'West Zone (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 15000, transitDays: '3–5 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '302001', city: 'Jaipur', state: 'Rajasthan', zone: 'North Zone (Inter-State)', prepaid: true, cod: true, reversePickup: true, maxWeightGrams: 12000, transitDays: '4–5 business days', codFee: 40, effectiveDate: '2026-09-01' },
  { pincode: '790001', city: 'Itanagar', state: 'Arunachal Pradesh', zone: 'Special North-East Zone', prepaid: true, cod: false, reversePickup: false, maxWeightGrams: 5000, transitDays: '6–9 business days (Prepaid only, self-ship returns)', codFee: 0, effectiveDate: '2026-09-01' },
];

export const initialOrders: OrderRecord[] = [
  {
    id: 'ord_1001',
    orderNumber: 'KRG-2026-1001',
    idempotencyKey: 'idem_seed_1001',
    accessToken: 'tok_guest_1001_9f8a7b6c',
    customerId: 'cust_1',
    isGuest: false,
    customer: {
      name: 'Rahul Mehta',
      email: 'rahul.mehta@example.in',
      phone: '+91 98201 11223',
    },
    shippingAddress: {
      recipientName: 'Rahul Mehta',
      phone: '+91 98201 11223',
      line1: 'Flat 402, Sea Breeze Apartments, Worli Sea Face',
      locality: 'Worli',
      landmark: 'Near Worli Dairy',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400013',
      country: 'India',
    },
    paymentMethod: 'razorpay',
    acceptanceStatus: 'confirmed',
    paymentStatus: 'captured',
    manualPaymentStatus: 'not_applicable',
    codStatus: 'not_applicable',
    fulfilmentStatus: 'fulfilled',
    shipmentStatus: 'delivered',
    customerSummaryStatus: 'Delivered on 24 Sep 2026',
    currency: 'INR',
    subtotal: 33998,
    discountTotal: 500,
    couponCode: 'FESTIVE500',
    shippingCharge: 0,
    codFee: 0,
    taxTotal: 3589,
    cgstTotal: 0,
    sgstTotal: 0,
    igstTotal: 3589,
    supplyType: 'inter_state',
    grandTotal: 33498,
    grandTotalMinor: 3349800,
    refundedTotal: 0,
    pendingRefundTotal: 0,
    razorpayOrderId: 'order_RzpSeed1001',
    razorpayPaymentId: 'pay_RzpCapt1001',
    warehouseId: 'wh_blr_main',
    shipment: {
      carrierName: 'BlueDart Insured Air Express',
      awbNumber: 'BD892341001IN',
      trackingUrl: 'https://www.bluedart.com/tracking?awb=BD892341001IN',
      bookedAt: '2026-09-21T16:00:00+05:30',
      pickedUpAt: '2026-09-21T18:30:00+05:30',
      deliveredAt: '2026-09-24T14:15:00+05:30',
      estimatedDelivery: '24 Sep 2026',
      weightGrams: 2800,
      actualCarrierCost: 280,
    },
    invoiceNumber: 'INV-2627-0001',
    invoiceIssuedAt: '2026-09-21T15:30:00+05:30',
    lines: [
      {
        lineId: 'line_1001_1',
        productId: 'prod_mj_biker_black',
        variantId: 'var_prod_mj_biker_black_m',
        sku: 'KRG-LTH-MJ_BIKER_BLACK-M',
        title: 'Obsidian Full-Grain Leather Asymmetric Biker Jacket',
        size: 'M',
        color: 'Obsidian Black',
        image: '/images/mens_biker_black.jpg',
        qtyOrdered: 1,
        qtyAllocated: 1,
        qtyPacked: 1,
        qtyShipped: 1,
        qtyCancelled: 0,
        qtyReturned: 0,
        unitPrice: 18999,
        unitMrp: 24999,
        unitCost: 7800,
        allocatedDiscount: 280,
        taxableValue: 16713,
        gstRatePercent: 12,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 2006,
        lineTotalPayable: 18719,
        hsnCode: '42031010',
        categorySnapshot: 'Jackets & Racers',
        returnPolicySnapshot: '7_day_easy_return',
      },
      {
        lineId: 'line_1001_2',
        productId: 'prod_lg_duffel',
        variantId: 'var_prod_lg_duffel_one_size_45l',
        sku: 'KRG-LTH-LG_DUFFEL-ONE_SIZE_45L',
        title: 'The Voyager 45L Full-Grain Leather Weekend Duffle',
        size: 'One Size (45L)',
        color: 'Black & Bourbon Tan',
        image: '/images/leather_weekend_duffel.jpg',
        qtyOrdered: 1,
        qtyAllocated: 1,
        qtyPacked: 1,
        qtyShipped: 1,
        qtyCancelled: 0,
        qtyReturned: 0,
        unitPrice: 14999,
        unitMrp: 19999,
        unitCost: 5900,
        allocatedDiscount: 220,
        taxableValue: 12525,
        gstRatePercent: 18,
        cgstAmount: 0,
        sgstAmount: 0,
        igstAmount: 2254,
        lineTotalPayable: 14779,
        hsnCode: '42021110',
        categorySnapshot: 'Leather Goods & Bags',
        returnPolicySnapshot: '7_day_easy_return',
      },
    ],
    timeline: [
      { id: 'ev_1', timestamp: '2026-09-21T11:10:00+05:30', dimension: 'acceptance', fromState: 'draft', toState: 'placed', actor: 'customer:rahul.mehta@example.in', reason: 'Order placed via checkout', source: 'customer' },
      { id: 'ev_2', timestamp: '2026-09-21T11:11:00+05:30', dimension: 'payment', fromState: 'pending', toState: 'captured', actor: 'razorpay_webhook', reason: 'Verified signature for pay_RzpCapt1001', source: 'webhook' },
      { id: 'ev_3', timestamp: '2026-09-21T18:30:00+05:30', dimension: 'shipment', fromState: 'booked', toState: 'picked_up', actor: 'warehouse@store.com', reason: 'Handed over to BlueDart AWB BD892341001IN', source: 'admin' },
      { id: 'ev_4', timestamp: '2026-09-24T14:15:00+05:30', dimension: 'shipment', fromState: 'out_for_delivery', toState: 'delivered', actor: 'csv_import_job', reason: 'POD received by Rahul Mehta', source: 'admin' },
    ],
    attributedBannerId: 'sec_hero_1',
    attributedSectionId: 'sec_store_picks_3',
    createdAt: '2026-09-21T11:10:00+05:30',
    updatedAt: '2026-09-24T14:15:00+05:30',
  },
  {
    id: 'ord_1002',
    orderNumber: 'KRG-2026-1002',
    idempotencyKey: 'idem_seed_1002',
    accessToken: 'tok_guest_1002_3c4d5e6f',
    customerId: 'cust_2',
    isGuest: false,
    customer: {
      name: 'Ananya Nair',
      email: 'ananya.nair@example.in',
      phone: '+91 98450 55667',
    },
    shippingAddress: {
      recipientName: 'Ananya Nair',
      phone: '+91 98450 55667',
      line1: '78, 4th Cross, Defence Colony',
      locality: 'Indiranagar',
      landmark: 'Near Defence Colony Park',
      city: 'Bengaluru',
      state: 'Karnataka',
      pincode: '560038',
      country: 'India',
    },
    paymentMethod: 'manual_upi',
    acceptanceStatus: 'awaiting_review',
    paymentStatus: 'pending',
    manualPaymentStatus: 'submitted',
    codStatus: 'not_applicable',
    fulfilmentStatus: 'unallocated',
    shipmentStatus: 'not_started',
    customerSummaryStatus: 'Payment submitted, awaiting verification by Finance',
    currency: 'INR',
    subtotal: 17999,
    discountTotal: 0,
    couponCode: null,
    shippingCharge: 0,
    codFee: 0,
    taxTotal: 1928,
    cgstTotal: 964,
    sgstTotal: 964,
    igstTotal: 0,
    supplyType: 'intra_state_karnataka',
    grandTotal: 17999,
    grandTotalMinor: 1799900,
    refundedTotal: 0,
    pendingRefundTotal: 0,
    manualUpiClaim: {
      utrReference: '627018492011',
      paidAtClaimed: '2026-09-27T10:42:00+05:30',
      screenshotNote: 'Paid ₹17,999 via GPay to karigar@hdfcbank (UTR 627018492011)',
      submittedAt: '2026-09-27T10:43:10+05:30',
    },
    warehouseId: 'wh_blr_main',
    lines: [
      {
        lineId: 'line_1002_1',
        productId: 'prod_wj_biker_black',
        variantId: 'var_prod_wj_biker_black_s',
        sku: 'KRG-LTH-WJ_BIKER_BLACK-S',
        title: 'Cropped Obsidian Nappa Leather Biker Jacket',
        size: 'S',
        color: 'Obsidian Black',
        image: '/images/womens_biker_black.jpg',
        qtyOrdered: 1,
        qtyAllocated: 0,
        qtyPacked: 0,
        qtyShipped: 0,
        qtyCancelled: 0,
        qtyReturned: 0,
        unitPrice: 17999,
        unitMrp: 23499,
        unitCost: 7200,
        allocatedDiscount: 0,
        taxableValue: 16071,
        gstRatePercent: 12,
        cgstAmount: 964,
        sgstAmount: 964,
        igstAmount: 0,
        lineTotalPayable: 17999,
        hsnCode: '42031010',
        categorySnapshot: 'Jackets & Racers',
        returnPolicySnapshot: '7_day_easy_return',
      },
    ],
    timeline: [
      { id: 'ev_201', timestamp: '2026-09-27T10:40:00+05:30', dimension: 'acceptance', fromState: 'draft', toState: 'placed', actor: 'customer:ananya.nair@example.in', reason: 'Selected Manual UPI QR checkout', source: 'customer' },
      { id: 'ev_202', timestamp: '2026-09-27T10:43:10+05:30', dimension: 'manual_payment', fromState: 'awaiting_submission', toState: 'submitted', actor: 'customer:ananya.nair@example.in', reason: 'Customer submitted UTR 627018492011 for bank statement verification', source: 'customer' },
    ],
    attributedBannerId: 'sec_hero_1',
    attributedSectionId: 'sec_store_picks_3',
    createdAt: '2026-09-27T10:40:00+05:30',
    updatedAt: '2026-09-27T10:43:10+05:30',
  },
];

export const initialReviews = [
  {
    id: 'rev_1',
    productId: 'prod_mj_biker_black',
    productTitle: 'Obsidian Full-Grain Leather Asymmetric Biker Jacket',
    orderId: 'ord_1001',
    customerName: 'Rahul Mehta',
    city: 'Mumbai',
    rating: 5,
    title: 'Flawless 1.1mm lambskin that breaks in like butter',
    body: 'The leather grain has incredible depth without any artificial sheen. The heavy silver YKK zippers glide smoothly and the diamond-quilted shoulders give it a commanding silhouette. Fits true to size.',
    verifiedPurchase: true,
    helpfulCount: 22,
    status: 'published',
    fitFeedback: 'True to size',
    staffReply: 'Thank you, Rahul! Every Obsidian hide is grain-matched and tailored by our senior master cutter.',
    createdAt: '2026-09-25T11:20:00+05:30',
  },
  {
    id: 'rev_2',
    productId: 'prod_wsk_aline_black',
    productTitle: 'High-Waisted Black Leather A-Line Midi Skirt',
    orderId: 'ord_hist_88',
    customerName: 'Pooja Hegde',
    city: 'Bengaluru',
    rating: 5,
    title: 'The panel seams and walking slit are cut to perfection',
    body: 'Finding real full-grain leather skirts in India with proper breathability used to be impossible. The silk cupro lining keeps it light, and the front slit makes walking up stairs completely effortless.',
    verifiedPurchase: true,
    helpfulCount: 17,
    status: 'published',
    fitFeedback: 'True to size',
    staffReply: 'So glad you love the drape, Pooja! We designed the high-rise waistband specifically for all-day comfort.',
    createdAt: '2026-09-26T15:30:00+05:30',
  },
];

export const initialPromotions = [
  {
    id: 'promo_festive500',
    code: 'FESTIVE500',
    title: 'Atelier Bundle: Flat ₹500 Off on ₹2,500+',
    description: 'Order any two leather pieces totalling ₹2,500 or more and receive ₹500 off immediately.',
    type: 'fixed_amount',
    value: 500,
    minOrderAmount: 2500,
    maxDiscountCap: 500,
    autoApply: true,
    stackableWithFreeShipping: true,
    usageLimit: 500,
    usedCount: 42,
    enabled: true,
    startsAt: '2026-09-01T00:00:00+05:30',
    endsAt: '2026-12-31T23:59:59+05:30',
  },
  {
    id: 'promo_first10',
    code: 'WELCOME10',
    title: 'First Order Welcome Offer — 10% Off (Up to ₹2,000)',
    description: '10% off on your first leather atelier order above ₹5,000. Maximum discount cap of ₹2,000.',
    type: 'percentage',
    value: 10,
    minOrderAmount: 5000,
    maxDiscountCap: 2000,
    autoApply: false,
    stackableWithFreeShipping: true,
    usageLimit: 1000,
    usedCount: 118,
    enabled: true,
    startsAt: '2026-01-01T00:00:00+05:30',
    endsAt: '2026-12-31T23:59:59+05:30',
  },
];

export const initialWarehouses = [
  {
    id: 'wh_blr_main',
    code: 'BLR-INDIRANAGAR',
    name: 'Bengaluru Main Leather Atelier & Fulfilment Centre',
    city: 'Bengaluru',
    state: 'Karnataka',
    pincode: '560038',
    isDefault: true,
    bins: ['BIN-JACKETS-A1', 'BIN-COATS-A2', 'BIN-BOMBERS-B1', 'BIN-SKIRTS-C1', 'BIN-BAGS-D1', 'QUARANTINE-RTO-Q1'],
  },
  {
    id: 'wh_bom_workshop',
    code: 'BOM-PAREL',
    name: 'Mumbai Lower Parel Cutting Room & Reserve Vault',
    city: 'Mumbai',
    state: 'Maharashtra',
    pincode: '400013',
    isDefault: false,
    bins: ['BOM-HIDE-VAULT-R1', 'BOM-CUTTING-R2', 'BOM-DISPATCH-D1'],
  },
];

export const initialSuppliers = [
  {
    id: 'sup_kolhapur_guild',
    name: 'Shahu Heritage Leather & Tanning Guild',
    contactPerson: 'Prakash Shinde',
    phone: '+91 98220 33445',
    email: 'orders@shahuleather.in',
    leadTimeDays: 14,
    city: 'Kolhapur, Maharashtra',
    gstin: '27AABCS4455F1Z1',
  },
  {
    id: 'sup_ranipet_tannery',
    name: 'Ranipet Master Tannery & Leatherworks',
    contactPerson: 'K. Rajendran',
    phone: '+91 94440 22331',
    email: 'hides@ranipettannery.in',
    leadTimeDays: 12,
    city: 'Ranipet, Tamil Nadu',
    gstin: '33AABCR8877G1Z4',
  },
];

export const initialPurchaseOrders = [
  {
    id: 'po_2026_01',
    poNumber: 'PO-2026-089',
    supplierId: 'sup_kolhapur_guild',
    supplierName: 'Shahu Heritage Leather & Tanning Guild',
    warehouseId: 'wh_blr_main',
    status: 'partially_received',
    expectedDate: '2026-10-04',
    items: [
      { sku: 'KRG-LTH-MJ_BIKER_BLACK-L', title: 'Obsidian Full-Grain Leather Biker Jacket (L)', orderedQty: 15, receivedQty: 15, damagedQty: 0, unitCost: 7800 },
      { sku: 'KRG-LTH-WJ_BIKER_BLACK-M', title: 'Cropped Obsidian Nappa Biker Jacket (M)', orderedQty: 12, receivedQty: 12, damagedQty: 0, unitCost: 7200 },
    ],
    totalCost: 203400,
    createdAt: '2026-09-20T11:00:00+05:30',
  },
];

export const initialTickets = [
  {
    id: 'tkt_501',
    ticketNumber: 'SUP-2026-501',
    orderId: 'ord_1002',
    orderNumber: 'KRG-2026-1002',
    customerName: 'Ananya Nair',
    customerEmail: 'ananya.nair@example.in',
    subject: 'Submitted UPI UTR for Order KRG-2026-1002 — Indiranagar studio pickup inquiry',
    category: 'Payment & Pickup',
    priority: 'high',
    status: 'waiting_for_staff',
    assignedTo: 'Support & Finance',
    slaDueAt: '2026-09-27T16:45:00+05:30',
    messages: [
      {
        id: 'msg_1',
        sender: 'customer',
        author: 'Ananya Nair',
        timestamp: '2026-09-27T10:45:00+05:30',
        body: 'Hi team, I just paid ₹17,999 via GPay (UTR 627018492011) for the Cropped Nappa Biker. Once verified, can I try it on at your 12th Main Indiranagar studio this evening?',
        isInternalNote: false,
      },
    ],
    createdAt: '2026-09-27T10:45:00+05:30',
  },
];

export const initialReturns = [
  {
    id: 'ret_301',
    returnNumber: 'RET-2026-301',
    orderId: 'ord_1001',
    orderNumber: 'KRG-2026-1001',
    customerName: 'Rahul Mehta',
    customerEmail: 'rahul.mehta@example.in',
    lineId: 'line_1001_1',
    productTitle: 'Obsidian Full-Grain Leather Asymmetric Biker Jacket (M)',
    sku: 'KRG-LTH-MJ_BIKER_BLACK-M',
    qty: 1,
    reason: 'Size exchange for a looser layering fit (Exchange M for L)',
    preferredRemedy: 'exchange',
    replacementVariantSku: 'KRG-LTH-MJ_BIKER_BLACK-L',
    pickupMethod: 'reverse_pickup',
    status: 'under_review',
    inspectionNotes: 'Within 7-day return window. Replacement size L in stock.',
    refundAmount: 18999,
    createdAt: '2026-09-26T17:20:00+05:30',
  },
];

export const initialStaff = [
  { id: 'stf_1', name: 'Amit Deshmukh', email: 'superadmin@store.com', role: 'Owner / Super Admin', locationScope: 'All Locations (BLR & BOM)', mfaEnabled: true, active: true, permissions: ['*'] },
  { id: 'stf_2', name: 'Priya Sharma', email: 'finance@karigarstore.in', role: 'Finance & Reconciliation', locationScope: 'All Locations', mfaEnabled: true, active: true, permissions: ['payment.verify', 'refund.approve', 'refund.execute', 'reports.finance'] },
  { id: 'stf_3', name: 'Karthik Gowda', email: 'warehouse.blr@karigarstore.in', role: 'Warehouse Dispatcher', locationScope: 'BLR-INDIRANAGAR', mfaEnabled: true, active: true, permissions: ['stock.adjust', 'order.pack', 'shipment.update'] },
  { id: 'stf_4', name: 'Neha Verma', email: 'merchandising@karigarstore.in', role: 'Product & CMS Manager', locationScope: 'All Locations', mfaEnabled: true, active: true, permissions: ['product.publish', 'cms.publish', 'category.manage'] },
  { id: 'stf_5', name: 'Rohan Kulkarni', email: 'grievance@karigarstore.in', role: 'Customer Support & Grievance Officer', locationScope: 'All Locations', mfaEnabled: true, active: true, permissions: ['ticket.reply', 'return.review'] },
];

export const initialApprovals = [
  {
    id: 'apr_1',
    type: 'upi_qr_verification_policy',
    title: 'Approve Leather Hide Vault Transfer (BOM-PAREL to BLR-INDIRANAGAR)',
    requestedBy: 'warehouse.blr@karigarstore.in',
    amountOrQty: '40 Finished Hides (Obsidian Lambskin & Bourbon Cowhide)',
    reason: 'Replenish Bengaluru Studio safety stock for peak leather jacket season.',
    status: 'pending_approval',
    createdAt: '2026-09-27T08:30:00+05:30',
  },
];

export const initialAutomationRules = [
  {
    id: 'auto_1',
    name: 'Release Expired Unpaid Checkout Reservations',
    trigger: 'Every 15 minutes (Schedule)',
    condition: 'Order paymentStatus == pending AND reservation age > 30 mins (excluding Manual UPI submitted)',
    action: 'Release reserved variant stock & append stock_movement record',
    enabled: true,
    lastRunAt: '2026-09-27T13:00:00+05:30',
    runsCount: 148,
  },
  {
    id: 'auto_2',
    name: 'Escalate Manual UPI Claims Older Than 2 Business Hours',
    trigger: 'Order manualPaymentStatus == submitted',
    condition: 'Verification pending > 120 minutes during Mon-Sat 10:00–19:00 IST',
    action: 'Highlight in Today Queue & alert Finance role',
    enabled: true,
    lastRunAt: '2026-09-27T12:45:00+05:30',
    runsCount: 19,
  },
  {
    id: 'auto_3',
    name: 'Low Stock Threshold Replenishment Alert',
    trigger: 'Stock movement committed',
    condition: 'Variant available_to_promise <= lowStockThreshold',
    action: 'Create procurement draft task in Stock workspace',
    enabled: true,
    lastRunAt: '2026-09-27T11:30:00+05:30',
    runsCount: 12,
  },
];

export const initialAnalyticsRollups = {
  freshnessTimestamp: '2026-09-28T13:15:00+05:30',
  periodLabel: 'Last 30 Days (Asia/Kolkata)',
  businessTruth: {
    orderValuePlaced: 684650,
    confirmedMerchandiseSales: 618400,
    recognisedRevenueExTax: 552140,
    taxCollectedGst: 66260,
    cashReceiptsVerified: 542800,
    codPendingRemittance: 75600,
    manualUpiAwaitingVerification: 17999,
    refundsCompleted: 0,
    estimatedContributionMargin: 312400,
  },
  funnel: {
    uniqueSessions: 5820,
    productViewers: 3840,
    cartAdditions: 912,
    checkoutStarted: 448,
    ordersConfirmed: 184,
    zeroResultSearchRatePercent: 1.1,
  },
  sectionPerformance: [
    { sectionId: 'sec_hero_1', name: '01. Hero Campaign — Handcrafted Luxury Leather', visibleImpressions: 5420, clicks: 984, ctrPercent: 18.2, attributedOrders: 68, attributedRevenue: 1289000 },
    { sectionId: 'sec_categories_2', name: '02. Category Shortcuts', visibleImpressions: 4890, clicks: 1212, ctrPercent: 24.8, attributedOrders: 49, attributedRevenue: 894200 },
    { sectionId: 'sec_store_picks_3', name: '03. Signature Biker & Moto Collection', visibleImpressions: 4540, clicks: 840, ctrPercent: 18.5, attributedOrders: 38, attributedRevenue: 712000 },
    { sectionId: 'sec_story_origin_4', name: '04. Story 1 — Why We Built the Atelier', visibleImpressions: 3810, clicks: 490, ctrPercent: 12.8, attributedOrders: 19, attributedRevenue: 362900 },
    { sectionId: 'sec_story_products_5', name: '05. Tailored Longline Leather Coats', visibleImpressions: 3650, clicks: 588, ctrPercent: 16.1, attributedOrders: 24, attributedRevenue: 672000 },
  ],
};
""")
