import os
import json

def get_all_products_code():
    return '''import {
  ProductRecord,
  CategoryRecord,
  CollectionRecord,
  CMSSection,
  GlobalCMSSettings,
  CMSReleaseManifest,
  OrderRecord,
} from './types';

export const initialGlobalSettings: GlobalCMSSettings = {
  storeName: 'Karigar & Co.',
  storeTagline: 'Full-grain leather jackets, coats, skirts & goods.',
  legalEntityName: 'Karigar Everyday Apparel & Goods Pvt. Ltd.',
  gstin: '29AABCK4829L1Z5',
  foundingYear: 2019,
  announcementBar: {
    enabled: true,
    message: 'Free delivery on orders over ₹999',
    detailsLabel: 'Details',
    detailsHref: '/shipping',
    detailsModalText:
      'Orders with a payable merchandise value of ₹999 or above qualify for free insured delivery across serviceable Indian postcodes. Orders below ₹999 incur a flat ₹79 shipping charge. Unused leather garments with original tags intact are eligible for a 7-day size exchange or return from the date of delivery. Custom-altered garments are excluded from exchange. Cash on Delivery (COD) is available on eligible postcodes for orders up to ₹10,000 with a ₹40 cash handling fee.',
    startsAt: '2026-01-01T00:00:00+05:30',
    endsAt: null,
  },
  header: {
    logoText: 'KARIGAR & CO.',
    showPinChecker: true,
    defaultPin: '',
    navLinks: [
      { label: 'Shop All', href: '/products' },
      { label: 'Men', href: '/category/men-leather' },
      { label: 'Women', href: '/category/women-leather' },
      { label: 'New Arrivals', href: '/collection/new-arrivals' },
      { label: 'Our Story', href: '/story' },
    ],
  },
  footer: {
    aboutBlurb:
      'Started in a boutique cutting room in 2019 and headquartered at our Indiranagar, Bengaluru studio. We tailor full-grain lambskin, vegetable-tanned goat nappa, and box calf leather into timeless jackets, coats, and heritage accessories.',
    address: '123, 12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    phone: '+91 80 4123 9876',
    email: 'care@karigarstore.in',
    whatsapp: '+91 98765 43210',
    hours: 'Mon–Sat: 10:00 AM – 7:00 PM IST',
    grievanceOfficerName: 'Rohan Kulkarni (Grievance Redressal Officer)',
    grievanceOfficerEmail: 'grievance@karigarstore.in',
    showSuperAdminLink: true,
    superAdminLinkLabel: 'SA A/C',
  },
  colors: {
    ivory: '#F8F5ED',
    charcoal: '#18201B',
    gold: '#B28A50',
  },
};

export const initialCategories: CategoryRecord[] = [
  {
    id: 'cat_men_leather',
    slug: 'men-leather',
    name: "Men's Leather",
    description: "Full-grain leather biker jackets, café racers, bomber jackets, trucker jackets, and car coats for men.",
    parentId: null,
    ancestry: [],
    image: '/images/cat-men.jpg',
    imageAlt: "Men's obsidian full-grain leather biker jacket",
    order: 1,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'fabric', 'fit'],
    seoTitle: "Men's Luxury Leather Jackets, Racers & Coats | Karigar & Co.",
    seoDescription: "Shop handcrafted full-grain leather jackets for men in obsidian black, vintage tobacco, and oxblood red.",
  },
  {
    id: 'cat_women_leather',
    slug: 'women-leather',
    name: "Women's Leather",
    description: "Butter-soft leather biker jackets, cropped bombers, belted trench coats, and tailored leather skirts for women.",
    parentId: null,
    ancestry: [],
    image: '/images/cat-women.jpg',
    imageAlt: "Women's tailored cropped black leather biker jacket",
    order: 2,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'fabric', 'fit'],
    seoTitle: "Women's Luxury Leather Jackets, Coats & Skirts | Karigar & Co.",
    seoDescription: "Tailored women's leather apparel crafted from glove-soft Italian nappa and vegetable-tanned leather.",
  },
  {
    id: 'cat_jackets',
    slug: 'jackets',
    name: 'Jackets & Racers',
    description: 'Asymmetric leather biker jackets, minimalist café racers, and classic trucker jackets.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-jackets.jpg',
    imageAlt: 'Handcrafted leather biker and café racer jackets',
    order: 3,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Leather Biker & Café Racer Jackets | Karigar & Co.',
    seoDescription: 'Heavy-duty YKK hardware, full-grain lambskin, and ergonomic diamond quilting.',
  },
  {
    id: 'cat_coats',
    slug: 'coats',
    name: 'Coats & Trench',
    description: 'Tailored single-breasted leather car coats and double-breasted belted leather trench coats.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-coats.jpg',
    imageAlt: 'Saddle brown belted double-breasted leather trench coat',
    order: 4,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Luxury Leather Overcoats & Trench Coats | Karigar & Co.',
    seoDescription: 'Longline drape, storm flaps, matching leather tie belts, and silk-blend lining.',
  },
  {
    id: 'cat_bombers',
    slug: 'bombers',
    name: 'Bombers & Flight',
    description: 'Classic MA-1 ribbed knit bombers and A-2 aviator flight jackets with genuine shearling collars.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-bombers.jpg',
    imageAlt: 'A-2 aviator flight jacket with shearling collar',
    order: 5,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Leather Bomber & Flight Jackets | Karigar & Co.',
    seoDescription: 'Ribbed wool collar and hem trims, utility sleeve zips, and supple lambskin.',
  },
  {
    id: 'cat_skirts',
    slug: 'skirts',
    name: 'Leather Skirts',
    description: 'High-waisted A-line midi skirts with front slits, paneled pencil skirts, and buckle wrap mini skirts.',
    parentId: 'cat_women_leather',
    ancestry: ['cat_women_leather'],
    image: '/images/cat-skirts.jpg',
    imageAlt: 'High-waisted black leather A-line midi skirt',
    order: 6,
    archived: false,
    allowedFilters: ['size', 'color', 'price'],
    seoTitle: "Women's Leather Skirts — Midi, Pencil & Mini | Karigar & Co.",
    seoDescription: 'Precision paneled leather skirts in black, chestnut brown, and burgundy red.',
  },
  {
    id: 'cat_accessories',
    slug: 'accessories',
    name: 'Leather Goods & Bags',
    description: '45L weekend travel duffle bags, 16" commuter laptop briefcases, Chelsea boots, and bridle leather belts.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-accessories.jpg',
    imageAlt: 'Full-grain leather weekend duffel bag',
    order: 7,
    archived: false,
    allowedFilters: ['color', 'price'],
    seoTitle: 'Leather Duffle Bags, Briefcases & Belts | Karigar & Co.',
    seoDescription: 'Solid brass hardware, copper rivets, and full-grain vegetable-tanned leather.',
  },
  {
    id: 'cat_footwear',
    slug: 'footwear',
    name: 'Leather Footwear',
    description: 'Goodyear-welted black box calf Chelsea boots with stacked leather soles.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-footwear.jpg',
    imageAlt: 'Goodyear-welted black calfskin Chelsea boots',
    order: 8,
    archived: false,
    allowedFilters: ['size', 'price'],
    seoTitle: 'Handcrafted Leather Boots & Footwear | Karigar & Co.',
    seoDescription: 'Goodyear-welted construction with cushioned arch support.',
  },
];

export const initialCollections: CollectionRecord[] = [
  {
    id: 'col_all_leather',
    slug: 'all-leather',
    title: 'Signature Leather Collection',
    eyebrow: 'Full-Grain Masterworks',
    description: 'Our complete atelier catalogue of handcrafted leather jackets, longline coats, bombers, skirts, and bags.',
    campaignTerms: 'Free Insured Delivery on orders over ₹999 • 7-Day Doorstep Size Exchange.',
    bannerImage: '/images/hero-desktop.jpg',
    bannerAlt: 'Karigar luxury leather collection',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_wsk_aline_black', 'prod_wsk_pencil_brown', 'prod_wsk_wrap_red',
      'prod_mc_car_black', 'prod_mc_trench_brown', 'prod_mc_car_red',
      'prod_wc_trench_black', 'prod_wc_trench_brown', 'prod_wc_trench_red',
      'prod_mb_ma1_black', 'prod_mb_a2_brown', 'prod_mb_ma1_red',
      'prod_wb_ma1_black', 'prod_wb_aviator_brown', 'prod_wb_ribbed_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red',
      'prod_mt_trucker_black', 'prod_mt_trucker_brown', 'prod_mt_trucker_red',
      'prod_wt_trucker_black', 'prod_wt_trucker_brown', 'prod_wt_trucker_red',
      'prod_lg_duffel', 'prod_lg_briefcase', 'prod_fw_chelsea_black', 'prod_lg_belt_bourbon'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: '2026-01-01T00:00:00+05:30',
    endsAt: null,
    order: 1,
  },
  {
    id: 'col_mens_collection',
    slug: 'mens-leather',
    title: "Men's Handcrafted Leather",
    eyebrow: 'Architectural Cuts & Heavy Hardware',
    description: 'Biker jackets, café racers, A-2 shearling flight jackets, and tailored car coats built for decades of wear.',
    campaignTerms: 'Crafted from 1.1mm to 1.3mm drum-dyed full-grain hides.',
    bannerImage: '/images/cat-men.jpg',
    bannerAlt: "Men's leather collection banner",
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_mc_car_black', 'prod_mc_trench_brown', 'prod_mc_car_red',
      'prod_mb_ma1_black', 'prod_mb_a2_brown', 'prod_mb_ma1_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_mt_trucker_black', 'prod_mt_trucker_brown', 'prod_mt_trucker_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 2,
  },
  {
    id: 'col_womens_collection',
    slug: 'womens-leather',
    title: "Women's Luxury Leather & Skirts",
    eyebrow: 'Supple Nappa & Feminine Tailoring',
    description: 'Cropped moto jackets, longline belted trench coats, MA-1 bombers, and precision paneled leather skirts.',
    campaignTerms: 'Supple Italian-grade nappa leather with silk-blend linings.',
    bannerImage: '/images/cat-women.jpg',
    bannerAlt: "Women's leather collection banner",
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_wsk_aline_black', 'prod_wsk_pencil_brown', 'prod_wsk_wrap_red',
      'prod_wc_trench_black', 'prod_wc_trench_brown', 'prod_wc_trench_red',
      'prod_wb_ma1_black', 'prod_wb_aviator_brown', 'prod_wb_ribbed_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red',
      'prod_wt_trucker_black', 'prod_wt_trucker_brown', 'prod_wt_trucker_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 3,
  },
  {
    id: 'col_biker_racers',
    slug: 'biker-and-racers',
    title: 'Biker & Café Racer Jackets',
    eyebrow: 'Motorcycle Heritage',
    description: 'Asymmetric zips, mandarin snap collars, diamond quilting, and action-back shoulder pleats.',
    campaignTerms: 'Equipped with heavy-duty YKK metal zippers and solid brass snaps.',
    bannerImage: '/images/cat-jackets.jpg',
    bannerAlt: 'Biker and racer jackets banner',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 4,
  },
  {
    id: 'col_new_arrivals',
    slug: 'new-arrivals',
    title: 'New Atelier Arrivals',
    eyebrow: 'Fresh from the Workshop',
    description: 'Newly released A-2 shearling aviators, double-breasted trench coats, and buckle wrap skirts.',
    campaignTerms: 'Hand-inspected and ready for immediate dispatch from our Bengaluru studio.',
    bannerImage: '/images/cat-coats.jpg',
    bannerAlt: 'New arrival leather pieces',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mb_a2_brown', 'prod_mc_trench_brown', 'prod_wc_trench_black',
      'prod_wsk_wrap_red', 'prod_lg_duffel', 'prod_fw_chelsea_black'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 5,
  },
  {
    id: 'col_bestsellers',
    slug: 'bestsellers',
    title: 'Karigar Atelier Bestsellers',
    eyebrow: 'Customer Favorites',
    description: 'Our most sought-after leather jackets, car coats, and weekend travel bags.',
    campaignTerms: 'Backed by our 5-year leather hardware & seam repair guarantee.',
    bannerImage: '/images/cat-bombers.jpg',
    bannerAlt: 'Bestseller leather jackets',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_wj_biker_black', 'prod_mc_car_black',
      'prod_wsk_aline_black', 'prod_mr_racer_brown', 'prod_lg_duffel'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 6,
  },
];
'''
