import os
import json

seed_file_path = os.path.join(os.getcwd(), 'src', 'lib', 'seed.ts')

content = '''import {
  ProductRecord,
  CategoryRecord,
  CollectionRecord,
  CMSSection,
  GlobalCMSSettings,
  CMSReleaseManifest,
  OrderRecord,
} from './types';

export const initialGlobalSettings: GlobalCMSSettings = {
  storeName: 'Karigar & Co.',
  storeTagline: 'Handcrafted luxury leather jackets, tailored coats & artisan goods.',
  legalEntityName: 'Karigar Everyday Apparel & Goods Pvt. Ltd.',
  gstin: '29AABCK4829L1Z5',
  foundingYear: 2019,
  announcementBar: {
    enabled: true,
    message: 'Free insured delivery & 7-day doorstep size exchange across India on all leather orders over ₹999',
    detailsLabel: 'Details',
    detailsHref: '/shipping',
    detailsModalText:
      'All handcrafted leather jackets, coats, skirts, and bags qualify for free insured doorstep delivery across India. Pre-treated full-grain hides, verified YKK hardware, and individual master-artisan inspection certificate included with every piece. Cash on Delivery (COD) is available on eligible PIN codes up to ₹10,000.',
    startsAt: '2026-01-01T00:00:00+05:30',
    endsAt: null,
  },
  header: {
    logoText: 'KARIGAR & CO.',
    showPinChecker: true,
    defaultPin: '560038',
    navLinks: [
      { label: "Men's Leather", href: '/category/men-leather' },
      { label: "Women's Leather", href: '/category/women-leather' },
      { label: 'Jackets & Racers', href: '/category/jackets' },
      { label: 'Coats & Trench', href: '/category/coats' },
      { label: 'Bombers & Flight', href: '/category/bombers' },
      { label: 'Leather Skirts', href: '/category/skirts' },
      { label: 'Leather Goods', href: '/category/accessories' },
      { label: 'New Arrivals', href: '/collection/new-arrivals' },
      { label: 'Craft & Atelier', href: '/story' },
    ],
  },
  footer: {
    aboutBlurb:
      'Started in a boutique cutting room in 2019 and headquartered at our Indiranagar, Bengaluru studio. We tailor full-grain lambskin, vegetable-tanned goat nappa, and box calf leather into timeless jackets, coats, and heritage accessories.',
    address: '123, 12th Main Road, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560038',
    phone: '+91 80 4123 9876',
    email: 'care@karigarstore.in',
    whatsapp: '+91 98765 43210',
    hours: 'Mon–Sat: 10:00 AM – 7:00 PM IST',
    grievanceOfficerName: 'Rohan Kulkarni (Grievance Redressal Officer)',
    grievanceOfficerEmail: 'grievance@karigarstore.in',
    showSuperAdminLink: true,
    superAdminLinkLabel: 'SA A/C',
  },
  colors: {
    ivory: '#F8F5ED',
    charcoal: '#18201B',
    gold: '#B28A50',
  },
};

export const initialCategories: CategoryRecord[] = [
  {
    id: 'cat_men_leather',
    slug: 'men-leather',
    name: "Men's Leather",
    description: "Full-grain leather biker jackets, café racers, MA-1 bombers, western truckers, and single-breasted car coats for men.",
    parentId: null,
    ancestry: [],
    image: '/images/cat-men.jpg',
    imageAlt: "Men's obsidian full-grain leather biker jacket",
    order: 1,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'fabric', 'fit'],
    seoTitle: "Men's Luxury Leather Jackets, Racers & Coats | Karigar & Co.",
    seoDescription: "Shop handcrafted full-grain leather jackets for men in obsidian black, vintage tobacco, and oxblood red.",
  },
  {
    id: 'cat_women_leather',
    slug: 'women-leather',
    name: "Women's Leather",
    description: "Butter-soft leather moto jackets, cropped bombers, belted longline trench coats, and tailored leather skirts for women.",
    parentId: null,
    ancestry: [],
    image: '/images/cat-women.jpg',
    imageAlt: "Women's tailored cropped black leather biker jacket",
    order: 2,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'fabric', 'fit'],
    seoTitle: "Women's Luxury Leather Jackets, Coats & Skirts | Karigar & Co.",
    seoDescription: "Tailored women's leather apparel crafted from glove-soft Italian nappa and vegetable-tanned leather.",
  },
  {
    id: 'cat_jackets',
    slug: 'jackets',
    name: 'Jackets & Racers',
    description: 'Iconic asymmetric motorcycle bikers, minimalist café racers, and western trucker jackets.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-jackets.jpg',
    imageAlt: 'Handcrafted leather moto and biker jackets',
    order: 3,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Leather Biker & Café Racer Jackets | Karigar & Co.',
    seoDescription: 'Heavy-duty YKK hardware, full-grain lambskin, and ergonomic diamond quilting.',
  },
  {
    id: 'cat_coats',
    slug: 'coats',
    name: 'Coats & Trench',
    description: 'Tailored single-breasted leather car coats and double-breasted belted leather trench coats.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-coats.jpg',
    imageAlt: 'Saddle brown belted double-breasted leather trench coat',
    order: 4,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Luxury Leather Overcoats & Trench Coats | Karigar & Co.',
    seoDescription: 'Longline drape, storm flaps, matching leather tie belts, and silk-blend lining.',
  },
  {
    id: 'cat_bombers',
    slug: 'bombers',
    name: 'Bombers & Flight',
    description: 'Classic MA-1 ribbed knit bombers and A-2 aviator flight jackets with genuine shearling collars.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-bombers.jpg',
    imageAlt: 'A-2 aviator flight jacket with shearling collar',
    order: 5,
    archived: false,
    allowedFilters: ['size', 'color', 'price', 'genderScope'],
    seoTitle: 'Leather Bomber & Flight Jackets | Karigar & Co.',
    seoDescription: 'Ribbed wool collar and hem trims, utility sleeve zips, and supple lambskin.',
  },
  {
    id: 'cat_skirts',
    slug: 'skirts',
    name: 'Leather Skirts',
    description: 'High-waisted A-line midi skirts with front slits, paneled pencil skirts, and buckle wrap mini skirts.',
    parentId: 'cat_women_leather',
    ancestry: ['cat_women_leather'],
    image: '/images/cat-skirts.jpg',
    imageAlt: 'High-waisted black leather A-line midi skirt',
    order: 6,
    archived: false,
    allowedFilters: ['size', 'color', 'price'],
    seoTitle: "Women's Leather Skirts — Midi, Pencil & Mini | Karigar & Co.",
    seoDescription: 'Precision paneled leather skirts in black, chestnut brown, and burgundy red.',
  },
  {
    id: 'cat_accessories',
    slug: 'accessories',
    name: 'Leather Goods & Bags',
    description: '45L weekend travel duffle bags, 16" commuter laptop briefcases, Chelsea boots, and bridle leather belts.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-accessories.jpg',
    imageAlt: 'Full-grain leather weekend duffel bag',
    order: 7,
    archived: false,
    allowedFilters: ['color', 'price'],
    seoTitle: 'Leather Duffle Bags, Briefcases & Belts | Karigar & Co.',
    seoDescription: 'Solid brass hardware, copper rivets, and full-grain vegetable-tanned leather.',
  },
  {
    id: 'cat_footwear',
    slug: 'footwear',
    name: 'Leather Footwear',
    description: 'Goodyear-welted black box calf Chelsea boots with stacked leather soles.',
    parentId: null,
    ancestry: [],
    image: '/images/cat-footwear.jpg',
    imageAlt: 'Goodyear-welted black calfskin Chelsea boots',
    order: 8,
    archived: false,
    allowedFilters: ['size', 'price'],
    seoTitle: 'Handcrafted Leather Boots & Footwear | Karigar & Co.',
    seoDescription: 'Goodyear-welted construction with cushioned arch support.',
  },
];

export const initialCollections: CollectionRecord[] = [
  {
    id: 'col_all_leather',
    slug: 'all-leather',
    title: 'Signature Leather Collection',
    eyebrow: 'Full-Grain Masterworks',
    description: 'Our complete atelier catalogue of handcrafted leather jackets, longline coats, bombers, skirts, and bags.',
    campaignTerms: 'Free Insured Delivery on orders over ₹999 • 7-Day Doorstep Size Exchange.',
    bannerImage: '/images/hero-desktop.jpg',
    bannerAlt: 'Karigar luxury leather collection',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_wsk_aline_black', 'prod_wsk_pencil_brown', 'prod_wsk_wrap_red',
      'prod_mc_car_black', 'prod_mc_trench_brown', 'prod_mc_car_red',
      'prod_wc_trench_black', 'prod_wc_trench_brown', 'prod_wc_trench_red',
      'prod_mb_ma1_black', 'prod_mb_a2_brown', 'prod_mb_ma1_red',
      'prod_wb_ma1_black', 'prod_wb_aviator_brown', 'prod_wb_ribbed_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red',
      'prod_mt_trucker_black', 'prod_mt_trucker_brown', 'prod_mt_trucker_red',
      'prod_wt_trucker_black', 'prod_wt_trucker_brown', 'prod_wt_trucker_red',
      'prod_lg_duffel', 'prod_lg_briefcase', 'prod_fw_chelsea_black', 'prod_lg_belt_bourbon'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: '2026-01-01T00:00:00+05:30',
    endsAt: null,
    order: 1,
  },
  {
    id: 'col_mens_collection',
    slug: 'mens-leather',
    title: "Men's Handcrafted Leather",
    eyebrow: 'Architectural Cuts & Heavy Hardware',
    description: 'Biker jackets, café racers, A-2 shearling flight jackets, and tailored car coats built for decades of wear.',
    campaignTerms: 'Crafted from 1.1mm to 1.3mm drum-dyed full-grain hides.',
    bannerImage: '/images/cat-men.jpg',
    bannerAlt: "Men's leather collection banner",
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_mc_car_black', 'prod_mc_trench_brown', 'prod_mc_car_red',
      'prod_mb_ma1_black', 'prod_mb_a2_brown', 'prod_mb_ma1_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_mt_trucker_black', 'prod_mt_trucker_brown', 'prod_mt_trucker_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 2,
  },
  {
    id: 'col_womens_collection',
    slug: 'womens-leather',
    title: "Women's Luxury Leather & Skirts",
    eyebrow: 'Supple Nappa & Feminine Tailoring',
    description: 'Cropped moto jackets, longline belted trench coats, MA-1 bombers, and precision paneled leather skirts.',
    campaignTerms: 'Supple Italian-grade nappa leather with silk-blend linings.',
    bannerImage: '/images/cat-women.jpg',
    bannerAlt: "Women's leather collection banner",
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_wsk_aline_black', 'prod_wsk_pencil_brown', 'prod_wsk_wrap_red',
      'prod_wc_trench_black', 'prod_wc_trench_brown', 'prod_wc_trench_red',
      'prod_wb_ma1_black', 'prod_wb_aviator_brown', 'prod_wb_ribbed_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red',
      'prod_wt_trucker_black', 'prod_wt_trucker_brown', 'prod_wt_trucker_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 3,
  },
  {
    id: 'col_biker_racers',
    slug: 'biker-and-racers',
    title: 'Biker & Café Racer Jackets',
    eyebrow: 'Motorcycle Heritage',
    description: 'Asymmetric zips, mandarin snap collars, diamond quilting, and action-back shoulder pleats.',
    campaignTerms: 'Equipped with heavy-duty YKK metal zippers and solid brass snaps.',
    bannerImage: '/images/cat-jackets.jpg',
    bannerAlt: 'Biker and racer jackets banner',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_mj_biker_brown', 'prod_mj_biker_red',
      'prod_wj_biker_black', 'prod_wj_biker_brown', 'prod_wj_biker_red',
      'prod_mr_racer_black', 'prod_mr_racer_brown', 'prod_mr_racer_red',
      'prod_wr_racer_black', 'prod_wr_racer_brown', 'prod_wr_racer_red'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 4,
  },
  {
    id: 'col_new_arrivals',
    slug: 'new-arrivals',
    title: 'New Atelier Arrivals',
    eyebrow: 'Fresh from the Workshop',
    description: 'Newly released A-2 shearling aviators, double-breasted trench coats, and buckle wrap skirts.',
    campaignTerms: 'Hand-inspected and ready for immediate dispatch from our Bengaluru studio.',
    bannerImage: '/images/cat-coats.jpg',
    bannerAlt: 'New arrival leather pieces',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mb_a2_brown', 'prod_mc_trench_brown', 'prod_wc_trench_black',
      'prod_wsk_wrap_red', 'prod_lg_duffel', 'prod_fw_chelsea_black'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 5,
  },
  {
    id: 'col_bestsellers',
    slug: 'bestsellers',
    title: 'Karigar Atelier Bestsellers',
    eyebrow: 'Customer Favorites',
    description: 'Our most sought-after leather jackets, car coats, and weekend travel bags.',
    campaignTerms: 'Backed by our 5-year leather hardware & seam repair guarantee.',
    bannerImage: '/images/cat-bombers.jpg',
    bannerAlt: 'Bestseller leather jackets',
    mode: 'manual',
    matchType: 'ALL',
    rules: [],
    manualProductIds: [
      'prod_mj_biker_black', 'prod_wj_biker_black', 'prod_mc_car_black',
      'prod_wsk_aline_black', 'prod_mr_racer_brown', 'prod_lg_duffel'
    ],
    excludedProductIds: [],
    enabled: true,
    startsAt: null,
    endsAt: null,
    order: 6,
  },
];
'''

# Helper to construct product record
def make_product(pid, slug, title, subtitle, short_desc, desc, ptype, cat_id, cat_anc, col_ids, tags, price, mrp, cost, badge, img_url, alt, variants_data, attrs_dict, legal_dict, warranty):
    return {
        "id": pid,
        "slug": slug,
        "title": title,
        "subtitle": subtitle,
        "shortDescription": short_desc,
        "description": desc,
        "productType": ptype,
        "brand": "Karigar & Co.",
        "supplierId": "sup_kolhapur_guild",
        "categoryId": cat_id,
        "categoryAncestry": cat_anc,
        "collectionIds": col_ids,
        "tags": tags,
        "status": "published",
        "price": price,
        "mrp": mrp,
        "costPrice": cost,
        "badge": badge,
        "images": [{"id": f"img_{pid}_1", "url": img_url, "alt": alt, "focalPoint": {"x": 0.5, "y": 0.5}}],
        "variants": variants_data,
        "attributes": attrs_dict,
        "legalMetrology": legal_dict,
        "returnPolicyClass": "7_day_easy_return",
        "returnWindowDays": 7,
        "warrantySummary": warranty,
        "seo": {
            "title": f"{title} | Karigar & Co. Leather Atelier",
            "description": short_desc,
            "canonicalSlug": slug,
            "noindex": False
        },
        "relatedProductIds": [],
        "goesWellWithIds": ["prod_lg_duffel", "prod_lg_belt_bourbon", "prod_fw_chelsea_black"],
        "ratingAverage": 4.9,
        "ratingCount": 28,
        "reviewCount": 12,
        "createdAt": "2026-08-01T10:00:00+05:30",
        "updatedAt": "2026-09-28T12:00:00+05:30",
        "revision": 2
    }

# Generate 37 complete products
# Let's write the complete generator script
with open('scratch_build_seed.py', 'w', encoding='utf-8') as f:
    f.write('''import os
import json
from generate_all_seed_products import get_all_products_code, get_all_cms_sections_code, get_remaining_seed_code

with open("src/lib/seed.ts", "w", encoding="utf-8") as out:
    out.write(get_all_products_code())
    out.write(get_all_cms_sections_code())
    out.write(get_remaining_seed_code())

print("src/lib/seed.ts generated successfully!")
''')
